In [1]:
import numpy as np
import pandas as pd

In [2]:
# importing both the data frames by the name 'movies' and 'credits'
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
'''budget , genres , homepage
id , keywords , original_language
original_title , overview , popularity
production_companies , production_countries
release_date , revenue , runtime
spoken_languages
status
tagline
title
vote_average
vote_count '''

# these are all the columns

'budget , genres , homepage\nid , keywords , original_language\noriginal_title , overview , popularity\nproduction_companies , production_countries\nrelease_date , revenue , runtime\nspoken_languages\nstatus\ntagline\ntitle\nvote_average\nvote_count '

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [7]:
#credits.head(1)['cast'].values   #names of all actors comes here (same type of output will also come for 'crew')

In [8]:
#size of movies dataframe and credits dataframe
print(movies.shape)
print(credits.shape)

(4803, 20)
(4803, 4)

In [9]:
#now merging both of these data frames based on the title
movies.merge(credits,on = 'title').shape

(4809, 23)

In [10]:
#as we can see now the number of columns = 23 = (24-1 as one column was common on both the dataframes) 
''' now reassigning this merged dataframe to 'movies' itself ,that is now the main dataframe is called 
and stored in 'movies'  ''' 
movies = movies.merge(credits,on = 'title')

In [11]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [12]:
#movies['original_language'].value_counts()  # we can see there are 4510 movies in english lang and rest are in other languages

In [13]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [14]:
''' the columns that we will keep : '''
# genres
# movie_id
# keywords
# title
# overview
# cast `
# crew

movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [15]:
movies

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

# now using this dataframe we have to make a new dataframe which has only three columns 
# that include : movie_id, title , tags
# tags column = merge of (overview + genres + keywords + cast + crew)
''' before doing that we have to preprocess these columns and for cast and crew ,we will add only the first/top three
cast/crew member names and we would need to remove missing data and duplicate data'''

In [16]:
# lets see if there is any missing data

movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [17]:
''' we can see that there are three movies for which overview is not present ..so we will remove those movies as its
 only three in this case '''
#movies.dropna(inplace=True)   # dropping those movies
movies['overview']=movies['overview'].fillna("")

In [18]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [19]:
movies.isnull().sum()  #we can see now we don't have any missing data

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [20]:
# now checking if we have any duplicate data or not
movies.duplicated().sum()

0

In [21]:
#so there is no duplicate data

In [22]:
movies.iloc[0]

movie_id                                                19995
title                                                  Avatar
overview    In the 22nd century, a paraplegic Marine is di...
genres      [{"id": 28, "name": "Action"}, {"id": 12, "nam...
keywords    [{"id": 1463, "name": "culture clash"}, {"id":...
cast        [{"cast_id": 242, "character": "Jake Sully", "...
crew        [{"credit_id": "52fe48009251416c750aca23", "de...
Name: 0, dtype: object

In [23]:

movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [24]:
''' we want to convert this list of dictionary in this format == > ['Action', 'Adventure', 'Fantansy', 'SciFi']'''
# we will make a function that will do this task

''' def convert(obj):
    L = []
    for i in obj:
        L.append(i['name'])
    return L  '''

" def convert(obj):\n    L = []\n    for i in obj:\n        L.append(i['name'])\n    return L  "

In [25]:
# now the problem is that the output of movies.iloc[0].genres is actually a string ,so we need to convert
# this string into list so that we can pass it into convert function to get the correct ans

#import ast
#ast.literal_eval

In [26]:
import ast

def convert(obj):  # this obj is a string
    L = []
    for i in ast.literal_eval(obj):  # and in this step it will become a list
        L.append(i['name'])
    return L

In [27]:
movies['genres'].apply(convert)

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4809, dtype: object

In [28]:
movies['genres'] = movies['genres'].apply(convert)

In [29]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [30]:
# we will do the same things on 'keywords' column

movies['keywords'] = movies['keywords'].apply(convert)

In [31]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [32]:
#movies['cast'][0]

In [33]:
def convert3(obj):  # this obj is a string
    L = []
    counter = 0
    for i in ast.literal_eval(obj):  # and in this step it will become a list
        if(counter != 3):
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [34]:
movies['cast'] = movies['cast'].apply(convert3)

In [35]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [36]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [35]:
# movies['crew'][0]
# this has many dictinaries but we want only that dictionary which has the job: director and in that dict
# we need the 'name' value

def fetch_director(obj):  # this obj is a string
    L = []
    for i in ast.literal_eval(obj):  # and in this step it will become a list
        if(i['job'] == 'Director'):
            L.append(i['name'])
            break   # as we want only one director
    return L

In [36]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [37]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [38]:
movies['overview'][0]

# now we can see that the overview column is a string , we will convert this into a list so that we can
# concatanate this with other lists

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [39]:
#func = lambda x:x.split()
#movies['overview'].apply(func)
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
1351,222936,Aloha,A celebrated military contractor returns to th...,"[Drama, Comedy, Romance]","[love triangle, hawaii, satellite, military, d...","[Bradley Cooper, Emma Stone, Rachel McAdams]",[Cameron Crowe]
2860,28353,Def Jam's How to Be a Player,Dray is a young playboy whose only objective i...,"[Comedy, Romance]","[sex, party, friends, player]","[Bill Bellamy, Lark Voorhies, Bernie Mac]",[Lionel C. Martin]
2486,23169,Remember Me,Still reeling from a heartbreaking family even...,"[Drama, Romance]","[new york, father son relationship, grieving, ...","[Robert Pattinson, Emilie de Ravin, Pierce Bro...",[Allen Coulter]
3556,230266,Miss Julie,Over the course of a midsummer night in Ferman...,[Drama],"[love triangle, love, irish, valet, woman dire...","[Jessica Chastain, Colin Farrell, Samantha Mor...",[Liv Ullmann]
2091,85,Raiders of the Lost Ark,When Dr. Indiana Jones – the tweed-suited prof...,"[Adventure, Action]","[saving the world, riddle, nepal, himalaya, ca...","[Harrison Ford, Karen Allen, Paul Freeman]",[Steven Spielberg]

In [40]:
# now we need to remove the spaces in between --> eg : sam worthington will have two tags 'sam' and 'worthington'
# these are two diff tags pointing to the same person and lets say there is another name sam mendes  ... this 
# will also have the 'sam' tag ..so  recommender will get confused which person to find..thats why we will be removing
# the space in between the two words

In [41]:
movies['genres'].apply(lambda x: [i.replace(" ","") for i in x])

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres, Length: 4809, dtype: object

In [42]:
movies['genres'] = movies['genres'].apply(lambda x: [i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x: [i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x: [i.replace(" ","") for i in x])

In [43]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [44]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [45]:

movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [46]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [47]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [48]:
# now we only need three columns : movie_id,title,tags
# so we will create new dataframe which will have these three columns from movies dataframe

new_df = movies[['movie_id','title','tags']]

In [49]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [50]:
#new_df['tags'][0] # we want to connect all lists with space

In [51]:
new_df['tags'].apply(lambda x : " ".join(x))

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: tags, Length: 4809, dtype: object

In [52]:
new_df['tags'] = new_df['tags'].apply(lambda x : " ".join(x))

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_16776\3530946481.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x : " ".join(x))

In [53]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [54]:
new_df['title'] = new_df['title'].apply(lambda x : x.lower())

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_16776\2238006699.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['title'] = new_df['title'].apply(lambda x : x.lower())

In [55]:
new_df.head()

,movie_id,title,tags
0,19995,avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,pirates of the caribbean: at world's end,"Captain Barbossa, long believed to be dead, ha..."
2,206647,spectre,A cryptic message from Bond’s past sends him o...
3,49026,the dark knight rises,Following the death of District Attorney Harve...
4,49529,john carter,"John Carter is a war-weary, former military ca..."

In [56]:
new_df['tags'][0]   #in its output we have overview then genres then keywords and cast and director

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [57]:
#making all words in lowercase
new_df['tags'] = new_df['tags'].apply(lambda x :x.lower())

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_16776\3095159808.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x :x.lower())

In [58]:
new_df.head()

,movie_id,title,tags
0,19995,avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,pirates of the caribbean: at world's end,"captain barbossa, long believed to be dead, ha..."
2,206647,spectre,a cryptic message from bond’s past sends him o...
3,49026,the dark knight rises,following the death of district attorney harve...
4,49529,john carter,"john carter is a war-weary, former military ca..."

In [59]:
# now our task is to check the similarity of movies....we will use vectorisation for that
# converting text to vector ...known as text vectorisation ....we will be using 'bag of words' technique

in "bag of words" technique, we combine all the tags...and in that merged large text we will try to find the words
which were repeated the most ......in short we will calculate the frequency of all the words  ---> take top 5000 words(means the words that have greater frequency --> top 5000)

now in every movie tags for eg : we will check how many times the word "action" came ,"fiction","romantic" ,....5,3,0,1,2....
for next movie tag --> 4,6,5,1......(for eg) ...etc 

so in the end i will have a table with size(5000,5000) ==> (no of movies,most common 5000words) [ you can take any number of words ..5000,10,000 etc) ]


now this....5,3,0,1,2......(value at 5000 word)....is a 5000 dimensional vector

during this vectorisation we will not consider the stop words ...(example : "are","from","is","a","to")

In [60]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000,stop_words = 'english') # the 2nd attribute will
                                                                 # will remove the stop words of english language

In [61]:
# CountVectorizer returns a scipi sparse matrix by default ,we will convert it to a numpy array
vectors = cv.fit_transform(new_df['tags']).toarray()

In [62]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [64]:
cv.get_feature_names_out()   # these are the top 5000 words

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [66]:
# we will remove similar words by one word...like actor,actors...activity ,acitivities...etc
# we will use a process called steming ...example how it works---['loved','loving','love'] ==> ['love','love','love']
import nltk

In [67]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [68]:
def stem(text):
    y = []
    for i in text.split():  # string converted to list 
        y.append(ps.stem(i))   #converting every word to stem and storing it in y
    
    string = " ".join(y)  # again converting this list into a string   
    return string

In [69]:
#example:
print(ps.stem('loved'))
print(ps.stem('love'))
print(ps.stem('dancing'))
print(ps.stem('dance'))

love
love
danc
danc

In [70]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_16776\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [71]:
cv.get_feature_names()   # now we can see the stemmed words :)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930s',
 '1940s',
 '1950s',
 '1960s',
 '1970s',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '1999',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 '70s',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academic',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'addict',
 'addicted',
 'addiction',
 'adolescence',
 'adopt',
 'adopted',
 'adoption',
 'adopts',
 'adrienbrody',
 'adult',
 'adultery',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affect',
 'affection',
 'affections',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditsstinger',
 'afterlife',
 'aftermath',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aidanquinn',
 'aided',
 'aids',
 'ailing',
 'air',
 'airplane',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alex',
 'alfredhitchcock',
 'ali',
 'alice',
 'alien',
 'alieninvasion',
 'alienlife',
 'aliens',
 'alike',
 'alive',
 'allen',
 'alliance',
 'allied',
 'allies',
 'allow',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alter',
 'alternate',
 'alternative',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amateur',
 'amazing',
 'ambassador',
 'ambition',
 'ambitious',
 'ambulance',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americanfootball',
 'americans',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amusementpark',
 'amy',
 'amyadams',
 'amysmart',
 'analyst',
 'anarchiccomedy',
 'ancient',
 'ancientrome',
 'ancientworld',
 'anderson',
 'andiemacdowell',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angels',
 'anger',
 'anglee',
 'angry',
 'animal',
 'animalattack',
 'animalhorror',
 'animals',
 'animated',
 'animation',
 'anna',
 'annafaris',
 'anne',
 'annehathaway',
 'annemoss',
 'annettebening',
 'annie',
 'anniversary',
 'annual',
 'answer',
 'answers',
 'ant',
 'anthology',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthropomorphism',
 'anti',
 'antics',
 'antihero',
 'antoinefuqua',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apparent',
 'apparently',
 'appear',
 'appears',
 'apple',
 'appointed',
 'apprentice',
 'approach',
 'approaches',
 'approaching',
 'april',
 'arab',
 'arch',
 'archaeologist',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'arise',
 'aristocrat',
 'armed',
 'arms',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arrangedmarriage',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'arthur',
 'artificialintelligence',
 'artist',
 'artistic',
 'artists',
 'arts',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asia',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assistant',
 'assumes',
 'asteroid',
 'astronaut',
 'astronauts',
 'asylum',
 'athlete',
 'atomicbomb',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attempttoescape',
 'attending',
 'attends',
 'attention',
 'attic',
 'attitude',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'audience',
 'audiences',
 'audition',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'autism',
 'auto',
 'automobileracing',
 'avenge',
 'average',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'ax',
 'babe',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backgrounds',
 'bad',
 'bag',
 'bahamas',
 'bail',
 'balance',
 'ball',
 'ballet',
 'baltimore',
 'band',
 'bandits',
 'bangkok',
 'banished',
 'bank',
 'banker',
 'bankrobber',
 'bankrobbery',
 'bar',
 'barbrastreisand',
 'barely',
 'bargained',
 'barn',
 'barney',
 'baron',
 'barry',
 'barrylevinson',
 'barrysonnenfeld',
 'bars',
 'base',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemusical',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battlefield',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beating',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becky',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beings',
 'belief',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'bell',
 'beloved',
 'ben',
 'benaffleck',
 'beneath',
 'benfoster',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstiller',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bet',
 'beth',
 'betrayal',
 'betrayed',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'bible',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikini',
 'billhader',
 'billionaire',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billycrudup',
 'billycrystal',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bisexual',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarre',
 'black',
 'blackmagic',
 'blackmail',
 'blackpeople',
 'blacksmith',
 'blade',
 'blame',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blonde',
 'blood',
 'bloodsplatter',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'board',
 'boarding',
 'boardingschool',
 'boat',
 'bob',
 'bobby',
 'bobbyfarrelly',
 'bobhoskins',
 'bodies',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bombing',
 'bond',
 'bonds',
 'bone',
 'book',
 'books',
 'border',
 'bored',
 'boredom',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'boundaries',
 'bounty',
 'bountyhunter',
 'bourne',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyfriend',
 'boys',
 'bradleycooper',
 'bradpitt',
 'brain',
 'brand',
 'brave',
 'bravery',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'brendanfraser',
 'brendangleeson',
 'brent',
 'brettratner',
 'brian',
 'briandepalma',
 'bride',
 'bridge',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britishsecretservice',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'broker',
 'brooklyn',
 'brooks',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'bryansinger',
 'buck',
 'buddies',
 'buddy',
 'buddycomedy',
 'budget',
 'build',
 'building',
 'built',
 'bully',
 'bullying',
 'bumbling',
 'bunny',
 'burglar',
 'buried',
 'bus',
 'bush',
 'business',
 'businessman',
 'bust',
 'busy',
 'butler',
 'buy',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'called',
 'calls',
 'calvin',
 'camcorder',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'camping',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'candy',
 'cannibal',
 'capable',
 'capital',
 'capitalism',
 'capt',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraccident',
 'carchase',
 'carcrash',
 'card',
 'care',
 'career',
 'carefree',
 'caretaker',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrace',
 'carrie',
 'carry',
 'carrying',
 'cars',
 'cartel',
 'carter',
 'cartoon',
 'caryelwes',
 'case',
 'cases',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'cataclysm',
 'catastrophe',
 'catch',
 'catches',
 'cateblanchett',
 'catherinedeneuve',
 'catherinekeener',
 'catherinezeta',
 'catholic',
 'catholicism',
 'cattle',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cavalry',
 'cave',
 'cavemen',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'cellphone',
 'cemetery',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'ceremony',
 'certain',
 'chain',
 'chainsaw',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chaotic',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotte',
 'charm',
 'charming',
 'chase',
 'chased',
 'chases',
 'chauffeur',
 'chazzpalminteri',
 'cheating',
 'cheerleader',
 'chef',
 'chemical',
 'cher',
 'chevychase',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabuse',
 'childhero',
 'childhood',
 'childprodigy',
 'children',
 'chilling',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloëgracemoretz',
 'chloësevigny',
 'chocolate',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chris',
 'chriscolumbus',
 'chriscooper',
 'chrisevans',
 'chrishemsworth',
 'chrispine',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianity',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christine',
 'christmas',
 'christmasparty',
 'christopher',
 'christopherlloyd',
 'christophernolan',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'ciaránhinds',
 'cigarettesmoking',
 'cillianmurphy',
 'cinema',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civil',
 'civilian',
 'civilization',
 'civilwar',
 'claim',
 'claiming',
 'claims',
 'claire',
 'clairedanes',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdifferences',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'classroom',
 'claudevandamme',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climate',
 'climbing',
 'clinteastwood',
 'clique',
 'cliveowen',
 'clock',
 'clone',
 'cloning',
 'close',
 'closed',
 'closer',
 'club',
 'clubs',
 'clue',
 'clueless',
 'clues',
 'clutches',
 'coach',
 'coast',
 'cocaine',
 'cocky',
 'code',
 'cody',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrell',
 'colinfirth',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'college',
 'collide',
 'collision',
 'colonel',
 'colony',
 'color',
 'colorado',
 'colorful',
 'coma',
 'combat',
 'combined',
 'come',
 'comeback',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comet',
 'comfort',
 'comic',
 'comics',
 'coming',
 'comingofage',
 'comingout',
 'command',
 'commander',
 'commercial',
 'commit',
 'commitment',
 'committed',
 'common',
 'communication',
 'community',
 'companion',
 'company',
 'compete',
 'competing',
 'competition',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'composer',
 'computer',
 'computervirus',
 'conan',
 'concert',
 'conclusion',
 'condition',
 'confession',
 'confidence',
 'confident',
 'conflict',
 'confront',
 'confronted',
 'confused',
 'congress',
 'conman',
 'connected',
 'connection',
 'connell',
 'connor',
 'conquer',
 'conscience',
 'consequences',
 'conservative',
 'considered',
 'conspiracy',
 'constant',
 'constantly',
 'construction',
 'contact',
 'contain',
 'contemporary',
 'contend',
 'contest',
 'continue',
 'continues',
 'continuing',
 'contract',
 'control',
 'controlled',
 'controlling',
 'controversial',
 'convention',
 'converge',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cooking',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'core',
 'corner',
 'corners',
 'corporate',
 'corporation',
 'corpse',
 'corrupt',
 'corruption',
 'cost',
 ...]

In [72]:
movies.shape

(4809, 8)

In [73]:
# we have 4806 movies, that means we have 4806 vectors and every vector has 5000 numbers
# we have to calculate the distance of every movie with every other movie
# we wont be calculating the eucladian distance(tip to tip distance).....we will calculate the cosine distance (angle)
# if(angle == 0)  almost same,if it is 5,10...similar....90 - > dissimilar ...180 --> completely opposite
# hence for more similarity ,the distance has to be less
'''therefore  : similarity is inverse of distance'''

'therefore  : similarity is inverse of distance'

In [74]:
from sklearn.metrics.pairwise import cosine_similarity

In [75]:
similarity = cosine_similarity(vectors)  # we are storing all these diatnces in a variable called similarity
'''1st movie will be compared to 4806 movies ,2nd movie will be comp to 4806 movies and 4806th movie will be compared ot 
4806 movies ...hence size of similarity will be (4806,4806)'''

'1st movie will be compared to 4806 movies ,2nd movie will be comp to 4806 movies and 4806th movie will be compared ot \n4806 movies ...hence size of similarity will be (4806,4806)'

In [76]:
similarity.shape

(4809, 4809)

In [77]:
similarity  #array of arrays

array([[1.        , 0.08838835, 0.05892557, ..., 0.02457366, 0.02777778,
        0.        ],
       [0.08838835, 1.        , 0.0625    , ..., 0.0260643 , 0.        ,
        0.        ],
       [0.05892557, 0.0625    , 1.        , ..., 0.0260643 , 0.        ,
        0.        ],
       ...,
       [0.02457366, 0.0260643 , 0.0260643 , ..., 1.        , 0.07372098,
        0.04721922],
       [0.02777778, 0.        , 0.        , ..., 0.07372098, 1.        ,
        0.05337605],
       [0.        , 0.        , 0.        , ..., 0.04721922, 0.05337605,
        1.        ]])

In [78]:
similarity[0]

array([1.        , 0.08838835, 0.05892557, ..., 0.02457366, 0.02777778,
       0.        ])

In [79]:
# this is the similarity of 1st movie with 4806 movies.....so the similarity of the first movie with itself is 1 .
# and with others is as shown in the above output

In [80]:
similarity[1]   # 2nd movie --> 2nd movie ke saath similarity score is 1...so basically the diagonal of the similarity 
# matrix wil be one

array([0.08838835, 1.        , 0.0625    , ..., 0.0260643 , 0.        ,
       0.        ])

In [81]:
# we will make a function that will return the first 5 similar movies when given a movie name
'''first movie given --> find its index,using that index we will enter into the similarity matrix and 
will find that particular index movie ---- > we will get the similarity array (the distances ) and will sort those distances:
that is more similar movies will come in the beginning ....and then we will fetch the top five movies and display them'''

'first movie given --> find its index,using that index we will enter into the similarity matrix and \nwill find that particular index movie ---- > we will get the similarity array (the distances ) and will sort those distances:\nthat is more similar movies will come in the beginning ....and then we will fetch the top five movies and display them'

In [82]:
# now fetching the index of the given movie -- lets say "batman begins"
new_df['title'] == 'Avatar'

0       False
1       False
2       False
3       False
4       False
        ...
4804    False
4805    False
4806    False
4807    False
4808    False
Name: title, Length: 4809, dtype: bool

In [83]:
new_df[new_df['title'] == 'Avatar']  #masking

Empty DataFrame
Columns: [movie_id, title, tags]
Index: []

In [84]:
new_df[new_df['title'] == 'Avatar'].index

Int64Index([], dtype='int64')

In [85]:
#new_df[new_df['title'] == 'Avatar'].index[0]

In [86]:
#new_df[new_df['title'] == 'Batman Begins'].index[0]

In [87]:
# so the index of batman begins is 119

In [88]:
# now the problem that comes with sorting is that first of all it gets sorted in ascending order,we want it to be 
# in descending order and 2ndly when we sort the data the index gets lost ....meaning like initially the first index of 
# similarity is similarity of the given movie with the first movie,the value at 2nd posn shows the sim of the given movie
# with the 2nd movie and when we sort this array ..these indexes will get lost ,we dont want that to happen
# we want to hold the value of those indexes
# so we will use enumeration

In [89]:
similarity[0]

array([1.        , 0.08838835, 0.05892557, ..., 0.02457366, 0.02777778,
       0.        ])

In [90]:


enumerate(similarity[0])

In [91]:
list(enumerate(similarity[0]))  # now that list has become list of tuples

[(0, 1.0000000000000002),
 (1, 0.08838834764831843),
 (2, 0.05892556509887895),
 (3, 0.03928371006591931),
 (4, 0.1800205749557739),
 (5, 0.11669000700233413),
 (6, 0.022680460581325723),
 (7, 0.17391639824998364),
 (8, 0.06189844605901729),
 (9, 0.07624928516630233),
 (10, 0.1160517706371319),
 (11, 0.08006407690254357),
 (12, 0.0944911182523068),
 (13, 0.046676002800933654),
 (14, 0.11433239009500587),
 (15, 0.050832856777534886),
 (16, 0.08111071056538127),
 (17, 0.1481668148335556),
 (18, 0.11037769642208699),
 (19, 0.08606629658238703),
 (20, 0.05735393346764043),
 (21, 0.09284766908852593),
 (22, 0.06804138174397717),
 (23, 0.0944911182523068),
 (24, 0.05555555555555555),
 (25, 0.037986858819879316),
 (26, 0.1690308509457033),
 (27, 0.1849000654084097),
 (28, 0.12379689211803457),
 (29, 0.07001400420140048),
 (30, 0.07216878364870322),
 (31, 0.16037507477489604),
 (32, 0.08989331499509895),
 (33, 0.10425720702853739),
 (34, 0.0),
 (35, 0.11180339887498947),
 (36, 0.1917988185229168),
 (37, 0.08219949365267865),
 (38, 0.062017367294604234),
 (39, 0.08703882797784893),
 (40, 0.05555555555555555),
 (41, 0.14433756729740643),
 (42, 0.0),
 (43, 0.09622504486493763),
 (44, 0.04042260417272216),
 (45, 0.08989331499509895),
 (46, 0.17407765595569785),
 (47, 0.21339479988815996),
 (48, 0.0668153104781061),
 (49, 0.0629940788348712),
 (50, 0.1217161238900369),
 (51, 0.08535791995526398),
 (52, 0.14506471329641488),
 (53, 0.050832856777534886),
 (54, 0.034752402342845795),
 (55, 0.07749842582921285),
 (56, 0.14213381090374028),
 (57, 0.028583097523751468),
 (58, 0.046676002800933654),
 (59, 0.07911877721292354),
 (60, 0.028583097523751468),
 (61, 0.2182178902359924),
 (62, 0.08084520834544431),
 (63, 0.09072184232530289),
 (64, 0.030949223029508643),
 (65, 0.020672455764868078),
 (66, 0.02457365935914952),
 (67, 0.17960530202677488),
 (68, 0.13333333333333333),
 (69, 0.051298917604257706),
 (70, 0.08451542547285165),
 (71, 0.08111071056538127),
 (72, 0.1217161238900369),
 (73, 0.03726779962499649),
 (74, 0.22116293423234568),
 (75, 0.08980265101338746),
 (76, 0.07624928516630233),
 (77, 0.014617633655117155),
 (78, 0.050251890762960605),
 (79, 0.07808688094430304),
 (80, 0.034020690871988585),
 (81, 0.11547005383792512),
 (82, 0.08219949365267865),
 (83, 0.2187974872468418),
 (84, 0.14360673947588817),
 (85, 0.10425720702853739),
 (86, 0.08703882797784893),
 (87, 0.1160517706371319),
 (88, 0.08980265101338746),
 (89, 0.060357164028345685),
 (90, 0.0629940788348712),
 (91, 0.15474611514754322),
 (92, 0.06933752452815364),
 (93, 0.050251890762960605),
 (94, 0.16343011261515333),
 (95, 0.12286829679574761),
 (96, 0.08838834764831843),
 (97, 0.07453559924999299),
 (98, 0.08451542547285165),
 (99, 0.029012942659282975),
 (100, 0.07273929674533079),
 (101, 0.08703882797784893),
 (102, 0.11037769642208699),
 (103, 0.08753762190648169),
 (104, 0.05802588531856595),
 (105, 0.10660035817780521),
 (106, 0.044151078568834795),
 (107, 0.09072184232530289),
 (108, 0.16666666666666666),
 (109, 0.07856742013183862),
 (110, 0.024056261216234408),
 (111, 0.1496710850223124),
 (112, 0.08980265101338746),
 (113, 0.05270462766947299),
 (114, 0.052057920629535355),
 (115, 0.05479966243511909),
 (116, 0.0563436169819011),
 (117, 0.05986843400892497),
 (118, 0.017376201171422898),
 (119, 0.048621663832631515),
 (120, 0.0),
 (121, 0.08838834764831843),
 (122, 0.09622504486493762),
 (123, 0.12155415958157878),
 (124, 0.06741998624632421),
 (125, 0.07874259854358899),
 (126, 0.11433239009500587),
 (127, 0.13471506281091264),
 (128, 0.0),
 (129, 0.10286889997472794),
 (130, 0.0314970394174356),
 (131, 0.10959932487023819),
 (132, 0.044946657497549475),
 (133, 0.03268602252303067),
 (134, 0.13333333333333333),
 (135, 0.0),
 (136, 0.025416428388767443),
 (137, 0.034020690871988585),
 (138, 0.08111071056538127),
 (139, 0.10669739994407998),
 (140, 0.050251890762960605),
 (141, 0.11470786693528086),
 (142, 0.09805806756909201),
 (143, 0.06804138174397717),
 (144, 0.05407380704358751),
 (145, 0.022075539284417398),
 (146, 0.017099639201419235),
 (147, 0.06189844605901729),
 (148, 0.10425720702853739),
 (149, 0.17071583991052797),
 (150, 0.18605210188381271),
 (151, 0.20211302086361077),
 (152, 0.0629940788348712),
 (153, 0.08466675133346033),
 (154, 0.03268602252303067),
 (155, 0.0),
 (156, 0.06565321642986127),
 (157, 0.10425720702853739),
 (158, 0.15075567228888181),
 (159, 0.06666666666666667),
 (160, 0.09496714704969829),
 (161, 0.034752402342845795),
 (162, 0.036369648372665396),
 (163, 0.05270462766947299),
 (164, 0.09128709291752768),
 (165, 0.049690399499995326),
 (166, 0.1178511301977579),
 (167, 0.06804138174397717),
 (168, 0.15811388300841897),
 (169, 0.11785113019775792),
 (170, 0.09072184232530289),
 (171, 0.029012942659282975),
 (172, 0.14907119849998596),
 (173, 0.024310831916315757),
 (174, 0.10959932487023819),
 (175, 0.050832856777534886),
 (176, 0.030429030972509225),
 (177, 0.0),
 (178, 0.025416428388767443),
 (179, 0.07647191129018724),
 (180, 0.022680460581325723),
 (181, 0.023338001400466827),
 (182, 0.10540925533894598),
 (183, 0.07362101738323101),
 (184, 0.1800205749557739),
 (185, 0.05479966243511909),
 (186, 0.0401286176952564),
 (187, 0.1388888888888889),
 (188, 0.0222717701593687),
 (189, 0.08084520834544431),
 (190, 0.08268982305947231),
 (191, 0.05143444998736397),
 (192, 0.0),
 (193, 0.08679260732054925),
 (194, 0.0),
 (195, 0.06415002990995841),
 (196, 0.05802588531856595),
 (197, 0.047619047619047616),
 (198, 0.05892556509887895),
 (199, 0.11446713662390752),
 (200, 0.07856742013183862),
 (201, 0.0),
 (202, 0.034020690871988585),
 (203, 0.08703882797784893),
 (204, 0.025717224993681984),
 (205, 0.08084520834544431),
 (206, 0.09558988911273406),
 (207, 0.08451542547285165),
 (208, 0.16666666666666666),
 (209, 0.03726779962499649),
 (210, 0.05407380704358751),
 (211, 0.027036903521793755),
 (212, 0.07537783614444091),
 (213, 0.06454972243679027),
 (214, 0.029012942659282975),
 (215, 0.07293249574894728),
 (216, 0.06415002990995841),
 (217, 0.045360921162651446),
 (218, 0.041666666666666664),
 (219, 0.06537204504606134),
 (220, 0.18257418583505536),
 (221, 0.024310831916315757),
 (222, 0.0890870806374748),
 (223, 0.08219949365267865),
 (224, 0.0625),
 (225, 0.052057920629535355),
 (226, 0.029462782549439476),
 (227, 0.09128709291752768),
 (228, 0.1256297269074015),
 (229, 0.07802743146408704),
 (230, 0.08830215713766959),
 (231, 0.0),
 (232, 0.1178511301977579),
 (233, 0.10660035817780521),
 (234, 0.0668153104781061),
 (235, 0.05986843400892497),
 (236, 0.09622504486493762),
 (237, 0.06950480468569159),
 (238, 0.1259881576697424),
 (239, 0.10849075915068655),
 (240, 0.050832856777534886),
 (241, 0.08838834764831843),
 (242, 0.09284766908852593),
 (243, 0.09829463743659808),
 (244, 0.06189844605901729),
 (245, 0.08980265101338746),
 (246, 0.06509445549041193),
 (247, 0.0),
 (248, 0.046225016352102424),
 (249, 0.14213381090374028),
 (250, 0.0),
 (251, 0.041666666666666664),
 (252, 0.022473328748774737),
 (253, 0.06509445549041193),
 (254, 0.08111071056538127),
 (255, 0.0),
 (256, 0.08084520834544431),
 (257, 0.08574929257125441),
 (258, 0.023112508176051212),
 (259, 0.0629940788348712),
 (260, 0.23947373603569988),
 (261, 0.025125945381480302),
 (262, 0.07071067811865475),
 (263, 0.10425720702853739),
 (264, 0.0),
 (265, 0.029012942659282975),
 (266, 0.10959932487023819),
 (267, 0.07106690545187014),
 (268, 0.027036903521793755),
 (269, 0.03268602252303067),
 (270, 0.10050378152592121),
 (271, 0.07808688094430304),
 (272, 0.030429030972509225),
 (273, 0.023570226039551584),
 (274, 0.07945521577046602),
 (275, 0.1217161238900369),
 (276, 0.06804138174397717),
 (277, 0.06565321642986127),
 (278, 0.10050378152592121),
 (279, 0.10286889997472794),
 (280, 0.0),
 (281, 0.07216878364870322),
 (282, 0.030429030972509225),
 (283, 0.0),
 (284, 0.0200643088476282),
 (285, 0.022473328748774737),
 (286, 0.0222717701593687),
 (287, 0.026688025634181187),
 (288, 0.0),
 (289, 0.04914731871829904),
 (290, 0.06537204504606134),
 (291, 0.0563436169819011),
 (292, 0.1),
 (293, 0.0314970394174356),
 (294, 0.1178511301977579),
 (295, 0.10814761408717502),
 (296, 0.040723148118768406),
 (297, 0.046676002800933654),
 (298, 0.0),
 (299, 0.041030496993110906),
 (300, 0.18446619684315546),
 (301, 0.1805787796286538),
 (302, 0.05986843400892497),
 (303, 0.029012942659282975),
 (304, 0.07106690545187014),
 (305, 0.19050019050028574),
 (306, 0.09284766908852593),
 (307, 0.10314212462587934),
 (308, 0.06950480468569159),
 (309, 0.06537204504606134),
 (310, 0.03533326266687867),
 (311, 0.15430334996209188),
 (312, 0.10814761408717502),
 (313, 0.07856742013183862),
 (314, 0.0),
 (315, 0.09128709291752768),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.06950480468569159),
 (320, 0.03333333333333333),
 (321, 0.0),
 (322, 0.22222222222222227),
 (323, 0.03333333333333333),
 (324, 0.026028960314767677),
 (325, 0.10910894511799618),
 (326, 0.05892556509887895),
 (327, 0.028583097523751468),
 (328, 0.0),
 (329, 0.08219949365267865),
 (330, 0.10959932487023819),
 (331, 0.04914731871829904),
 (332, 0.14291548761875733),
 (333, 0.030429030972509225),
 (334, 0.10540925533894598),
 (335, 0.05555555555555555),
 (336, 0.07273929674533079),
 (337, 0.023809523809523808),
 (338, 0.0),
 (339, 0.0563436169819011),
 (340, 0.052057920629535355),
 (341, 0.06085806194501845),
 (342, 0.13471506281091267),
 (343, 0.022473328748774737),
 (344, 0.030949223029508643),
 (345, 0.023338001400466827),
 (346, 0.0),
 (347, 0.0),
 (348, 0.06666666666666667),
 (349, 0.09128709291752768),
 (350, 0.05407380704358751),
 (351, 0.0),
 (352, 0.029012942659282975),
 (353, 0.023570226039551584),
 (354, 0.0),
 (355, 0.03928371006591931),
 (356, 0.08980265101338746),
 (357, 0.0),
 (358, 0.06537204504606134),
 (359, 0.034020690871988585),
 (360, 0.0),
 (361, 0.0563436169819011),
 (362, 0.09622504486493762),
 (363, 0.0890870806374748),
 (364, 0.025717224993681984),
 (365, 0.08006407690254357),
 (366, 0.05802588531856595),
 (367, 0.0),
 (368, 0.13333333333333333),
 (369, 0.14291548761875733),
 (370, 0.05555555555555555),
 (371, 0.10166571355506977),
 (372, 0.05270462766947299),
 (373, 0.17376201171422898),
 (374, 0.043768810953240846),
 (375, 0.042333375666730164),
 (376, 0.048112522432468816),
 (377, 0.0),
 (378, 0.0),
 (379, 0.05270462766947298),
 (380, 0.027777777777777776),
 (381, 0.0890870806374748),
 (382, 0.0),
 (383, 0.050251890762960605),
 (384, 0.032075014954979206),
 (385, 0.0),
 (386, 0.022893427324781505),
 (387, 0.027036903521793755),
 (388, 0.0),
 (389, 0.09805806756909201),
 (390, 0.027777777777777776),
 (391, 0.060633906259083235),
 (392, 0.030949223029508643),
 (393, 0.0),
 (394, 0.025717224993681984),
 (395, 0.0563436169819011),
 (396, 0.023338001400466827),
 (397, 0.05479966243511909),
 (398, 0.0),
 (399, 0.025416428388767443),
 (400, 0.10206207261596575),
 (401, 0.0314970394174356),
 (402, 0.06189844605901729),
 (403, 0.10942202738310211),
 (404, 0.06666666666666667),
 (405, 0.030429030972509225),
 (406, 0.021516574145596757),
 (407, 0.021884405476620423),
 (408, 0.036369648372665396),
 (409, 0.0),
 (410, 0.10050378152592121),
 (411, 0.057166195047502935),
 (412, 0.10050378152592121),
 (413, 0.1388888888888889),
 (414, 0.032075014954979206),
 (415, 0.07027283689263064),
 (416, 0.05479966243511909),
 (417, 0.034020690871988585),
 (418, 0.03726779962499649),
 (419, 0.07453559924999299),
 (420, 0.1270821419438372),
 (421, 0.0),
 (422, 0.14547859349066158),
 (423, 0.05143444998736397),
 (424, 0.0401286176952564),
 (425, 0.07001400420140048),
 (426, 0.06108472217815261),
 (427, 0.030949223029508643),
 (428, 0.05892556509887897),
 (429, 0.0),
 (430, 0.052057920629535355),
 (431, 0.025717224993681984),
 (432, 0.12422599874998833),
 (433, 0.03268602252303067),
 (434, 0.0),
 (435, 0.03928371006591931),
 (436, 0.0),
 (437, 0.028583097523751468),
 (438, 0.02817180849095055),
 (439, 0.030429030972509225),
 (440, 0.02817180849095055),
 (441, 0.029934217004462485),
 (442, 0.048112522432468816),
 (443, 0.05802588531856595),
 (444, 0.0),
 (445, 0.02817180849095055),
 (446, 0.025416428388767443),
 (447, 0.023570226039551584),
 (448, 0.025416428388767443),
 (449, 0.057166195047502935),
 (450, 0.026028960314767677),
 (451, 0.025717224993681984),
 (452, 0.0314970394174356),
 (453, 0.026028960314767677),
 (454, 0.1228682967957476),
 (455, 0.025416428388767443),
 (456, 0.06933752452815364),
 (457, 0.08451542547285165),
 (458, 0.046676002800933654),
 (459, 0.03553345272593507),
 (460, 0.02817180849095055),
 (461, 0.181848241863327),
 (462, 0.0),
 (463, 0.034752402342845795),
 (464, 0.0),
 (465, 0.0),
 (466, 0.20851441405707477),
 (467, 0.08989331499509895),
 (468, 0.029934217004462485),
 (469, 0.07001400420140048),
 (470, 0.048621663832631515),
 (471, 0.08219949365267865),
 (472, 0.08333333333333333),
 (473, 0.10050378152592121),
 (474, 0.0),
 (475, 0.06741998624632421),
 (476, 0.10660035817780521),
 (477, 0.0),
 (478, 0.03928371006591931),
 (479, 0.09375732507716866),
 (480, 0.05143444998736397),
 (481, 0.0),
 (482, 0.029934217004462485),
 (483, 0.12830005981991682),
 (484, 0.034020690871988585),
 (485, 0.0563436169819011),
 (486, 0.05773502691896257),
 (487, 0.13900960937138318),
 (488, 0.07548513560963971),
 (489, 0.0),
 (490, 0.14907119849998596),
 (491, 0.08989331499509895),
 (492, 0.06189844605901729),
 (493, 0.01924500897298752),
 (494, 0.0),
 (495, 0.2132007163556104),
 (496, 0.0),
 (497, 0.0),
 (498, 0.07106690545187014),
 (499, 0.0),
 (500, 0.027777777777777776),
 (501, 0.08679260732054925),
 (502, 0.15075567228888181),
 (503, 0.08333333333333333),
 (504, 0.0),
 (505, 0.14213381090374028),
 (506, 0.036369648372665396),
 (507, 0.24498947175305572),
 (508, 0.11433239009500587),
 (509, 0.025416428388767443),
 (510, 0.10411584125907071),
 (511, 0.0944911182523068),
 (512, 0.05986843400892497),
 (513, 0.11433239009500587),
 (514, 0.05892556509887895),
 (515, 0.027036903521793755),
 (516, 0.025717224993681984),
 (517, 0.0),
 (518, 0.05479966243511909),
 (519, 0.0),
 (520, 0.0),
 (521, 0.028583097523751468),
 (522, 0.0),
 (523, 0.05143444998736397),
 (524, 0.0),
 (525, 0.02457365935914952),
 (526, 0.0),
 (527, 0.0),
 (528, 0.02457365935914952),
 (529, 0.12858612496840993),
 (530, 0.1),
 (531, 0.049690399499995326),
 (532, 0.022680460581325723),
 (533, 0.06950480468569159),
 (534, 0.08333333333333333),
 (535, 0.10814761408717502),
 (536, 0.07624928516630233),
 (537, 0.06950480468569159),
 (538, 0.0),
 (539, 0.25724787771376323),
 (540, 0.05555555555555555),
 (541, 0.06804138174397717),
 (542, 0.0401286176952564),
 (543, 0.08703882797784893),
 (544, 0.05986843400892497),
 (545, 0.02817180849095055),
 (546, 0.07106690545187014),
 (547, 0.08838834764831843),
 (548, 0.0),
 (549, 0.12422599874998831),
 (550, 0.02817180849095055),
 (551, 0.043396303660274624),
 (552, 0.0),
 (553, 0.032075014954979206),
 (554, 0.0),
 (555, 0.049029033784546004),
 (556, 0.028583097523751468),
 (557, 0.14085904245475275),
 (558, 0.0),
 (559, 0.032075014954979206),
 (560, 0.045360921162651446),
 (561, 0.036369648372665396),
 (562, 0.0),
 (563, 0.027036903521793755),
 (564, 0.1),
 (565, 0.045360921162651446),
 (566, 0.02457365935914952),
 (567, 0.029934217004462485),
 (568, 0.14291548761875733),
 (569, 0.023809523809523808),
 (570, 0.07453559924999298),
 (571, 0.021698151830137312),
 (572, 0.08466675133346033),
 (573, 0.0222717701593687),
 (574, 0.024056261216234408),
 (575, 0.0563436169819011),
 (576, 0.028583097523751468),
 (577, 0.15214515486254612),
 (578, 0.047619047619047616),
 (579, 0.1217161238900369),
 (580, 0.024845199749997663),
 (581, 0.16343011261515333),
 (582, 0.24056261216234406),
 (583, 0.050832856777534886),
 (584, 0.050251890762960605),
 (585, 0.0),
 (586, 0.044946657497549475),
 (587, 0.07808688094430304),
 (588, 0.028583097523751468),
 (589, 0.08399210511316159),
 (590, 0.034020690871988585),
 (591, 0.07715167498104596),
 (592, 0.026352313834736494),
 (593, 0.0),
 (594, 0.05479966243511909),
 (595, 0.13344012817090595),
 (596, 0.09335200560186731),
 (597, 0.057166195047502935),
 (598, 0.03928371006591931),
 (599, 0.03316790634033297),
 (600, 0.07142857142857142),
 (601, 0.036588086663230115),
 (602, 0.0445435403187374),
 (603, 0.057166195047502935),
 (604, 0.06950480468569159),
 (605, 0.0),
 (606, 0.0),
 (607, 0.06622661785325219),
 (608, 0.0),
 (609, 0.04714045207910317),
 (610, 0.05976143046671968),
 (611, 0.024310831916315757),
 (612, 0.07001400420140048),
 (613, 0.03823595564509362),
 (614, 0.05986843400892497),
 (615, 0.03268602252303067),
 (616, 0.0),
 (617, 0.05479966243511909),
 (618, 0.09622504486493763),
 (619, 0.0),
 (620, 0.0),
 (621, 0.06804138174397717),
 (622, 0.021884405476620423),
 (623, 0.0),
 (624, 0.12126781251816647),
 (625, 0.0314970394174356),
 (626, 0.08980265101338746),
 (627, 0.11470786693528086),
 (628, 0.0),
 (629, 0.04914731871829904),
 (630, 0.024845199749997663),
 (631, 0.027036903521793755),
 (632, 0.08111071056538127),
 (633, 0.023570226039551584),
 (634, 0.08574929257125441),
 (635, 0.07453559924999299),
 (636, 0.02817180849095055),
 (637, 0.052057920629535355),
 (638, 0.03553345272593507),
 (639, 0.0),
 (640, 0.050832856777534886),
 (641, 0.0),
 (642, 0.0),
 (643, 0.10540925533894598),
 (644, 0.057166195047502935),
 (645, 0.047619047619047616),
 (646, 0.0563436169819011),
 (647, 0.052057920629535355),
 (648, 0.03268602252303067),
 (649, 0.0),
 (650, 0.0),
 (651, 0.0),
 (652, 0.024056261216234408),
 (653, 0.12126781251816647),
 (654, 0.08830215713766959),
 (655, 0.025717224993681984),
 (656, 0.0),
 (657, 0.03681050869161551),
 (658, 0.05270462766947299),
 (659, 0.026688025634181187),
 (660, 0.10206207261596575),
 (661, 0.16798421022632318),
 (662, 0.0),
 (663, 0.0),
 (664, 0.06415002990995841),
 (665, 0.07808688094430304),
 (666, 0.05143444998736397),
 (667, 0.0),
 (668, 0.06950480468569159),
 (669, 0.03553345272593507),
 (670, 0.017471413945365305),
 (671, 0.05270462766947299),
 (672, 0.0563436169819011),
 (673, 0.022680460581325723),
 (674, 0.07624928516630233),
 (675, 0.050832856777534886),
 (676, 0.03268602252303067),
 (677, 0.027399831217559546),
 (678, 0.06189844605901729),
 (679, 0.0),
 (680, 0.08219949365267865),
 (681, 0.034752402342845795),
 (682, 0.023809523809523808),
 (683, 0.050251890762960605),
 (684, 0.0),
 (685, 0.03726779962499649),
 (686, 0.0),
 (687, 0.1178511301977579),
 (688, 0.050251890762960605),
 (689, 0.0),
 (690, 0.029012942659282975),
 (691, 0.1),
 (692, 0.11904761904761904),
 (693, 0.0),
 (694, 0.0222717701593687),
 (695, 0.06804138174397717),
 (696, 0.0),
 (697, 0.0),
 (698, 0.023338001400466827),
 (699, 0.0),
 (700, 0.030429030972509225),
 (701, 0.06415002990995841),
 (702, 0.024056261216234408),
 (703, 0.020672455764868078),
 (704, 0.07293249574894728),
 (705, 0.025125945381480302),
 (706, 0.026028960314767677),
 (707, 0.0),
 (708, 0.025125945381480302),
 (709, 0.0),
 (710, 0.044151078568834795),
 (711, 0.06537204504606134),
 (712, 0.0),
 (713, 0.027036903521793755),
 (714, 0.0),
 (715, 0.10425720702853739),
 (716, 0.034752402342845795),
 (717, 0.0),
 (718, 0.04578685464956301),
 (719, 0.0),
 (720, 0.027036903521793755),
 (721, 0.03268602252303067),
 (722, 0.0),
 (723, 0.026352313834736494),
 (724, 0.025717224993681984),
 (725, 0.0),
 (726, 0.0),
 (727, 0.03594425773447947),
 (728, 0.07453559924999299),
 (729, 0.0),
 (730, 0.01642215463607155),
 (731, 0.05407380704358751),
 (732, 0.07808688094430304),
 (733, 0.044151078568834795),
 (734, 0.049690399499995326),
 (735, 0.04914731871829904),
 (736, 0.032075014954979206),
 (737, 0.07905694150420949),
 (738, 0.0),
 (739, 0.03823595564509362),
 (740, 0.1301448015738384),
 (741, 0.05802588531856595),
 (742, 0.034020690871988585),
 (743, 0.025416428388767443),
 (744, 0.06666666666666667),
 (745, 0.06189844605901729),
 (746, 0.08574929257125441),
 (747, 0.023338001400466827),
 (748, 0.03726779962499649),
 (749, 0.0),
 (750, 0.050832856777534886),
 (751, 0.03726779962499649),

In [92]:
'''now this is showing that similarity of 0th movie with 1st movie is 1, similarity of 0th movie with 2nd movie is 
0.896..... similarity of 0th movie with 3rd movie is 0.59.....  etc'''

'now this is showing that similarity of 0th movie with 1st movie is 1, similarity of 0th movie with 2nd movie is \n0.896..... similarity of 0th movie with 3rd movie is 0.59.....  etc'

In [93]:
sorted(list(enumerate(similarity[0])),reverse = True)  # reverse = True condition for sorting in descending
#order (highest similarity movie at the top)

[(4808, 0.0),
 (4807, 0.027777777777777776),
 (4806, 0.02457365935914952),
 (4805, 0.05270462766947299),
 (4804, 0.02457365935914952),
 (4803, 0.0),
 (4802, 0.05802588531856595),
 (4801, 0.020998026278290397),
 (4800, 0.0),
 (4799, 0.0),
 (4798, 0.0),
 (4797, 0.0),
 (4796, 0.05892556509887895),
 (4795, 0.0),
 (4794, 0.0),
 (4793, 0.0314970394174356),
 (4792, 0.022680460581325723),
 (4791, 0.0),
 (4790, 0.023112508176051212),
 (4789, 0.0),
 (4788, 0.0),
 (4787, 0.0445435403187374),
 (4786, 0.0),
 (4785, 0.026688025634181187),
 (4784, 0.0629940788348712),
 (4783, 0.022680460581325723),
 (4782, 0.0),
 (4781, 0.0),
 (4780, 0.05270462766947299),
 (4779, 0.0),
 (4778, 0.03268602252303067),
 (4777, 0.0),
 (4776, 0.029462782549439476),
 (4775, 0.026028960314767677),
 (4774, 0.041666666666666664),
 (4773, 0.0),
 (4772, 0.0),
 (4771, 0.0),
 (4770, 0.03823595564509362),
 (4769, 0.017972128867239735),
 (4768, 0.0),
 (4767, 0.0),
 (4766, 0.0),
 (4765, 0.0),
 (4764, 0.0314970394174356),
 (4763, 0.0),
 (4762, 0.023809523809523808),
 (4761, 0.0),
 (4760, 0.048112522432468816),
 (4759, 0.0),
 (4758, 0.027399831217559546),
 (4757, 0.0314970394174356),
 (4756, 0.0),
 (4755, 0.029462782549439476),
 (4754, 0.0),
 (4753, 0.0),
 (4752, 0.0),
 (4751, 0.025125945381480302),
 (4750, 0.0),
 (4749, 0.0),
 (4748, 0.0),
 (4747, 0.03268602252303067),
 (4746, 0.017766726362967535),
 (4745, 0.0445435403187374),
 (4744, 0.036369648372665396),
 (4743, 0.0),
 (4742, 0.027399831217559546),
 (4741, 0.0),
 (4740, 0.0890870806374748),
 (4739, 0.0),
 (4738, 0.0),
 (4737, 0.0),
 (4736, 0.0),
 (4735, 0.0),
 (4734, 0.029934217004462485),
 (4733, 0.026352313834736494),
 (4732, 0.0),
 (4731, 0.0),
 (4730, 0.06666666666666667),
 (4729, 0.0),
 (4728, 0.0),
 (4727, 0.0),
 (4726, 0.0),
 (4725, 0.019641855032959656),
 (4724, 0.0),
 (4723, 0.030429030972509225),
 (4722, 0.0),
 (4721, 0.08606629658238703),
 (4720, 0.0),
 (4719, 0.0),
 (4718, 0.0),
 (4717, 0.0),
 (4716, 0.026028960314767677),
 (4715, 0.0),
 (4714, 0.02021130208636108),
 (4713, 0.0),
 (4712, 0.0),
 (4711, 0.0),
 (4710, 0.02817180849095055),
 (4709, 0.012782749814122838),
 (4708, 0.0),
 (4707, 0.06537204504606134),
 (4706, 0.036369648372665396),
 (4705, 0.0),
 (4704, 0.0),
 (4703, 0.036369648372665396),
 (4702, 0.032075014954979206),
 (4701, 0.0),
 (4700, 0.0),
 (4699, 0.017376201171422898),
 (4698, 0.022680460581325723),
 (4697, 0.023809523809523808),
 (4696, 0.029934217004462485),
 (4695, 0.0),
 (4694, 0.029462782549439476),
 (4693, 0.025416428388767443),
 (4692, 0.0),
 (4691, 0.0),
 (4690, 0.0),
 (4689, 0.0),
 (4688, 0.0),
 (4687, 0.0),
 (4686, 0.0),
 (4685, 0.01807753815155468),
 (4684, 0.0),
 (4683, 0.032075014954979206),
 (4682, 0.0),
 (4681, 0.0),
 (4680, 0.0),
 (4679, 0.0),
 (4678, 0.028583097523751468),
 (4677, 0.02817180849095055),
 (4676, 0.1259881576697424),
 (4675, 0.049690399499995326),
 (4674, 0.0),
 (4673, 0.020833333333333332),
 (4672, 0.029934217004462485),
 (4671, 0.0),
 (4670, 0.032075014954979206),
 (4669, 0.034020690871988585),
 (4668, 0.0),
 (4667, 0.030949223029508643),
 (4666, 0.0),
 (4665, 0.0),
 (4664, 0.0314970394174356),
 (4663, 0.0),
 (4662, 0.0),
 (4661, 0.0),
 (4660, 0.08838834764831843),
 (4659, 0.022473328748774737),
 (4658, 0.0),
 (4657, 0.09245003270420485),
 (4656, 0.0),
 (4655, 0.034020690871988585),
 (4654, 0.0),
 (4653, 0.0),
 (4652, 0.0),
 (4651, 0.0),
 (4650, 0.0222717701593687),
 (4649, 0.0445435403187374),
 (4648, 0.0),
 (4647, 0.0),
 (4646, 0.046225016352102424),
 (4645, 0.036369648372665396),
 (4644, 0.08333333333333333),
 (4643, 0.07905694150420949),
 (4642, 0.0),
 (4641, 0.07106690545187014),
 (4640, 0.0),
 (4639, 0.05892556509887895),
 (4638, 0.043033148291193514),
 (4637, 0.027399831217559546),
 (4636, 0.026352313834736494),
 (4635, 0.03726779962499649),
 (4634, 0.0),
 (4633, 0.018633899812498245),
 (4632, 0.030949223029508643),
 (4631, 0.0),
 (4630, 0.0),
 (4629, 0.09128709291752768),
 (4628, 0.0),
 (4627, 0.05270462766947299),
 (4626, 0.10660035817780521),
 (4625, 0.0),
 (4624, 0.0),
 (4623, 0.025717224993681984),
 (4622, 0.0),
 (4621, 0.032075014954979206),
 (4620, 0.0),
 (4619, 0.0),
 (4618, 0.0),
 (4617, 0.0),
 (4616, 0.0),
 (4615, 0.0),
 (4614, 0.036369648372665396),
 (4613, 0.0),
 (4612, 0.0),
 (4611, 0.0),
 (4610, 0.04267895997763199),
 (4609, 0.0),
 (4608, 0.0),
 (4607, 0.03823595564509362),
 (4606, 0.0),
 (4605, 0.05555555555555555),
 (4604, 0.0),
 (4603, 0.0),
 (4602, 0.0),
 (4601, 0.0),
 (4600, 0.050251890762960605),
 (4599, 0.05270462766947299),
 (4598, 0.0),
 (4597, 0.041666666666666664),
 (4596, 0.0),
 (4595, 0.0),
 (4594, 0.06950480468569159),
 (4593, 0.024845199749997663),
 (4592, 0.029012942659282975),
 (4591, 0.0),
 (4590, 0.046225016352102424),
 (4589, 0.0),
 (4588, 0.0),
 (4587, 0.0),
 (4586, 0.0),
 (4585, 0.038749212914606423),
 (4584, 0.0),
 (4583, 0.0),
 (4582, 0.0),
 (4581, 0.0),
 (4580, 0.0),
 (4579, 0.026028960314767677),
 (4578, 0.0314970394174356),
 (4577, 0.0),
 (4576, 0.041666666666666664),
 (4575, 0.0),
 (4574, 0.0),
 (4573, 0.03268602252303067),
 (4572, 0.029934217004462485),
 (4571, 0.08084520834544431),
 (4570, 0.0),
 (4569, 0.06415002990995841),
 (4568, 0.01567868113972662),
 (4567, 0.0445435403187374),
 (4566, 0.0),
 (4565, 0.0),
 (4564, 0.0),
 (4563, 0.06415002990995841),
 (4562, 0.043033148291193514),
 (4561, 0.026688025634181187),
 (4560, 0.03928371006591931),
 (4559, 0.0),
 (4558, 0.0445435403187374),
 (4557, 0.03823595564509362),
 (4556, 0.027777777777777776),
 (4555, 0.024310831916315757),
 (4554, 0.0),
 (4553, 0.0),
 (4552, 0.030949223029508643),
 (4551, 0.0),
 (4550, 0.0),
 (4549, 0.0),
 (4548, 0.10583343916682542),
 (4547, 0.0),
 (4546, 0.029012942659282975),
 (4545, 0.0445435403187374),
 (4544, 0.0),
 (4543, 0.029462782549439476),
 (4542, 0.0),
 (4541, 0.06933752452815364),
 (4540, 0.0),
 (4539, 0.030429030972509225),
 (4538, 0.03726779962499649),
 (4537, 0.0),
 (4536, 0.05555555555555555),
 (4535, 0.018751465015433733),
 (4534, 0.0),
 (4533, 0.024845199749997663),
 (4532, 0.024056261216234408),
 (4531, 0.050251890762960605),
 (4530, 0.0),
 (4529, 0.0),
 (4528, 0.021884405476620423),
 (4527, 0.0),
 (4526, 0.0),
 (4525, 0.0),
 (4524, 0.0),
 (4523, 0.0),
 (4522, 0.05892556509887895),
 (4521, 0.0),
 (4520, 0.0),
 (4519, 0.09245003270420485),
 (4518, 0.0),
 (4517, 0.0),
 (4516, 0.0),
 (4515, 0.04914731871829904),
 (4514, 0.0),
 (4513, 0.029012942659282975),
 (4512, 0.0),
 (4511, 0.0),
 (4510, 0.0),
 (4509, 0.021698151830137312),
 (4508, 0.0),
 (4507, 0.0),
 (4506, 0.0),
 (4505, 0.09245003270420485),
 (4504, 0.0),
 (4503, 0.0),
 (4502, 0.0),
 (4501, 0.026688025634181187),
 (4500, 0.0),
 (4499, 0.0),
 (4498, 0.0),
 (4497, 0.0),
 (4496, 0.0),
 (4495, 0.08606629658238703),
 (4494, 0.0),
 (4493, 0.13608276348795434),
 (4492, 0.0),
 (4491, 0.0),
 (4490, 0.0),
 (4489, 0.0),
 (4488, 0.034020690871988585),
 (4487, 0.02457365935914952),
 (4486, 0.0),
 (4485, 0.03268602252303067),
 (4484, 0.0),
 (4483, 0.0),
 (4482, 0.0),
 (4481, 0.0),
 (4480, 0.0),
 (4479, 0.0),
 (4478, 0.0),
 (4477, 0.0),
 (4476, 0.08333333333333333),
 (4475, 0.07106690545187014),
 (4474, 0.0),
 (4473, 0.0),
 (4472, 0.026688025634181187),
 (4471, 0.09284766908852593),
 (4470, 0.0),
 (4469, 0.020998026278290397),
 (4468, 0.0),
 (4467, 0.0),
 (4466, 0.03928371006591931),
 (4465, 0.0),
 (4464, 0.0),
 (4463, 0.03928371006591931),
 (4462, 0.032075014954979206),
 (4461, 0.026688025634181187),
 (4460, 0.0),
 (4459, 0.0),
 (4458, 0.0),
 (4457, 0.0),
 (4456, 0.05270462766947299),
 (4455, 0.0),
 (4454, 0.08006407690254357),
 (4453, 0.026688025634181187),
 (4452, 0.0),
 (4451, 0.0),
 (4450, 0.0),
 (4449, 0.026352313834736494),
 (4448, 0.0),
 (4447, 0.0),
 (4446, 0.07453559924999298),
 (4445, 0.0),
 (4444, 0.0),
 (4443, 0.0),
 (4442, 0.0),
 (4441, 0.0),
 (4440, 0.0),
 (4439, 0.0),
 (4438, 0.0),
 (4437, 0.0),
 (4436, 0.03268602252303067),
 (4435, 0.0),
 (4434, 0.0),
 (4433, 0.08333333333333333),
 (4432, 0.0),
 (4431, 0.041666666666666664),
 (4430, 0.0),
 (4429, 0.025416428388767443),
 (4428, 0.0),
 (4427, 0.0),
 (4426, 0.0),
 (4425, 0.0),
 (4424, 0.02817180849095055),
 (4423, 0.034752402342845795),
 (4422, 0.029934217004462485),
 (4421, 0.0),
 (4420, 0.0),
 (4419, 0.0),
 (4418, 0.0),
 (4417, 0.0),
 (4416, 0.0),
 (4415, 0.030429030972509225),
 (4414, 0.07856742013183862),
 (4413, 0.0),
 (4412, 0.028583097523751468),
 (4411, 0.0),
 (4410, 0.034020690871988585),
 (4409, 0.0),
 (4408, 0.029462782549439476),
 (4407, 0.19245008972987526),
 (4406, 0.0),
 (4405, 0.07453559924999298),
 (4404, 0.032075014954979206),
 (4403, 0.026352313834736494),
 (4402, 0.03928371006591931),
 (4401, 0.048621663832631515),
 (4400, 0.0),
 (4399, 0.022473328748774737),
 (4398, 0.0),
 (4397, 0.0),
 (4396, 0.0),
 (4395, 0.0),
 (4394, 0.025125945381480302),
 (4393, 0.0),
 (4392, 0.04042260417272216),
 (4391, 0.0),
 (4390, 0.018518518518518517),
 (4389, 0.0),
 (4388, 0.0),
 (4387, 0.0),
 (4386, 0.046676002800933654),
 (4385, 0.026688025634181187),
 (4384, 0.05143444998736397),
 (4383, 0.0),
 (4382, 0.029012942659282975),
 (4381, 0.0),
 (4380, 0.0),
 (4379, 0.057166195047502935),
 (4378, 0.0),
 (4377, 0.048112522432468816),
 (4376, 0.0),
 (4375, 0.0),
 (4374, 0.027036903521793755),
 (4373, 0.025416428388767443),
 (4372, 0.0),
 (4371, 0.05270462766947299),
 (4370, 0.041666666666666664),
 (4369, 0.0),
 (4368, 0.0),
 (4367, 0.043033148291193514),
 (4366, 0.0),
 (4365, 0.0),
 (4364, 0.0445435403187374),
 (4363, 0.0),
 (4362, 0.0),
 (4361, 0.024056261216234408),
 (4360, 0.023570226039551584),
 (4359, 0.06950480468569159),
 (4358, 0.0),
 (4357, 0.06666666666666667),
 (4356, 0.0),
 (4355, 0.09245003270420485),
 (4354, 0.0),
 (4353, 0.03726779962499649),
 (4352, 0.0),
 (4351, 0.0314970394174356),
 (4350, 0.1386750490563073),
 (4349, 0.0),
 (4348, 0.0),
 (4347, 0.0),
 (4346, 0.0),
 (4345, 0.07216878364870322),
 (4344, 0.0),
 (4343, 0.029012942659282975),
 (4342, 0.0),
 (4341, 0.05892556509887895),
 (4340, 0.0),
 (4339, 0.0),
 (4338, 0.16012815380508713),
 (4337, 0.027036903521793755),
 (4336, 0.0),
 (4335, 0.046225016352102424),
 (4334, 0.04042260417272216),
 (4333, 0.10425720702853739),
 (4332, 0.041030496993110906),
 (4331, 0.0563436169819011),
 (4330, 0.0),
 (4329, 0.030429030972509225),
 (4328, 0.0),
 (4327, 0.02457365935914952),
 (4326, 0.03553345272593507),
 (4325, 0.0),
 (4324, 0.0),
 (4323, 0.0),
 (4322, 0.07106690545187014),
 (4321, 0.03456505649101417),
 (4320, 0.0),
 (4319, 0.027036903521793755),
 (4318, 0.05802588531856595),
 (4317, 0.0),
 (4316, 0.03928371006591931),
 (4315, 0.034020690871988585),
 (4314, 0.06537204504606134),
 (4313, 0.0),
 (4312, 0.0),
 (4311, 0.0),
 (4310, 0.0),
 (4309, 0.0),
 (4308, 0.0),
 (4307, 0.06154574548966636),
 (4306, 0.0),
 (4305, 0.0),
 (4304, 0.0),
 (4303, 0.0),
 (4302, 0.04042260417272216),
 (4301, 0.026688025634181187),
 (4300, 0.0),
 (4299, 0.0),
 (4298, 0.0),
 (4297, 0.0),
 (4296, 0.0),
 (4295, 0.05555555555555555),
 (4294, 0.03333333333333333),
 (4293, 0.0),
 (4292, 0.07273929674533079),
 (4291, 0.0),
 (4290, 0.027036903521793755),
 (4289, 0.0),
 (4288, 0.0),
 (4287, 0.0),
 (4286, 0.026352313834736494),
 (4285, 0.0),
 (4284, 0.034020690871988585),
 (4283, 0.05270462766947299),
 (4282, 0.023570226039551584),
 (4281, 0.048112522432468816),
 (4280, 0.0),
 (4279, 0.019374606457303212),
 (4278, 0.0),
 (4277, 0.0),
 (4276, 0.0),
 (4275, 0.0),
 (4274, 0.0),
 (4273, 0.0),
 (4272, 0.0),
 (4271, 0.0),
 (4270, 0.026028960314767677),
 (4269, 0.022893427324781505),
 (4268, 0.0),
 (4267, 0.027036903521793755),
 (4266, 0.026028960314767677),
 (4265, 0.026352313834736494),
 (4264, 0.0),
 (4263, 0.046225016352102424),
 (4262, 0.0),
 (4261, 0.08838834764831843),
 (4260, 0.0),
 (4259, 0.0),
 (4258, 0.10206207261596575),
 (4257, 0.0),
 (4256, 0.0),
 (4255, 0.0),
 (4254, 0.018294043331615058),
 (4253, 0.0),
 (4252, 0.029462782549439476),
 (4251, 0.0222717701593687),
 (4250, 0.04042260417272216),
 (4249, 0.0),
 (4248, 0.05270462766947299),
 (4247, 0.0),
 (4246, 0.0),
 (4245, 0.041666666666666664),
 (4244, 0.0),
 (4243, 0.0),
 (4242, 0.029462782549439476),
 (4241, 0.0),
 (4240, 0.027777777777777776),
 (4239, 0.022473328748774737),
 (4238, 0.0),
 (4237, 0.018751465015433733),
 (4236, 0.0314970394174356),
 (4235, 0.0),
 (4234, 0.0),
 (4233, 0.0),
 (4232, 0.10814761408717502),
 (4231, 0.0),
 (4230, 0.03553345272593507),
 (4229, 0.0),
 (4228, 0.0),
 (4227, 0.016835875742536845),
 (4226, 0.0),
 (4225, 0.0),
 (4224, 0.0),
 (4223, 0.0),
 (4222, 0.034752402342845795),
 (4221, 0.0),
 (4220, 0.0),
 (4219, 0.0),
 (4218, 0.06804138174397717),
 (4217, 0.027036903521793755),
 (4216, 0.0),
 (4215, 0.028583097523751468),
 (4214, 0.0),
 (4213, 0.029934217004462485),
 (4212, 0.0),
 (4211, 0.02817180849095055),
 (4210, 0.0),
 (4209, 0.0),
 (4208, 0.03928371006591931),
 (4207, 0.05479966243511909),
 (4206, 0.036369648372665396),
 (4205, 0.125),
 (4204, 0.03333333333333333),
 (4203, 0.0),
 (4202, 0.0),
 (4201, 0.0),
 (4200, 0.10660035817780521),
 (4199, 0.0),
 (4198, 0.06537204504606134),
 (4197, 0.03726779962499649),
 (4196, 0.025125945381480302),
 (4195, 0.034020690871988585),
 (4194, 0.2182178902359924),
 (4193, 0.0),
 (4192, 0.0),
 (4191, 0.0),
 (4190, 0.0),
 (4189, 0.027777777777777776),
 (4188, 0.0),
 (4187, 0.0),
 (4186, 0.034020690871988585),
 (4185, 0.0),
 (4184, 0.0),
 (4183, 0.07071067811865475),
 (4182, 0.04914731871829904),
 (4181, 0.023809523809523808),
 (4180, 0.0),
 (4179, 0.0),
 (4178, 0.0),
 (4177, 0.0),
 (4176, 0.0),
 (4175, 0.0),
 (4174, 0.0),
 (4173, 0.0),
 (4172, 0.0),
 (4171, 0.021166687833365082),
 (4170, 0.029462782549439476),
 (4169, 0.0),
 (4168, 0.032075014954979206),
 (4167, 0.08333333333333333),
 (4166, 0.0),
 (4165, 0.0),
 (4164, 0.0),
 (4163, 0.018993429409939658),
 (4162, 0.047619047619047616),
 (4161, 0.0),
 (4160, 0.0),
 (4159, 0.0),
 (4158, 0.0),
 (4157, 0.0),
 (4156, 0.04578685464956301),
 (4155, 0.0),
 (4154, 0.0),
 (4153, 0.0280717307022173),
 (4152, 0.0),
 (4151, 0.0),
 (4150, 0.0629940788348712),
 (4149, 0.0),
 (4148, 0.0),
 (4147, 0.0),
 (4146, 0.0),
 (4145, 0.0),
 (4144, 0.0),
 (4143, 0.0),
 (4142, 0.03268602252303067),
 (4141, 0.0),
 (4140, 0.0),
 (4139, 0.0200643088476282),
 (4138, 0.03726779962499649),
 (4137, 0.0),
 (4136, 0.11180339887498947),
 (4135, 0.06415002990995841),
 (4134, 0.0),
 (4133, 0.03823595564509362),
 (4132, 0.04042260417272216),
 (4131, 0.03928371006591931),
 (4130, 0.017099639201419235),
 (4129, 0.0),
 (4128, 0.025416428388767443),
 (4127, 0.0),
 (4126, 0.05555555555555555),
 (4125, 0.0),
 (4124, 0.07715167498104596),
 (4123, 0.0),
 (4122, 0.0),
 (4121, 0.06565321642986127),
 (4120, 0.0314970394174356),
 (4119, 0.0),
 (4118, 0.021884405476620423),
 (4117, 0.017190354104313223),
 (4116, 0.0),
 (4115, 0.030429030972509225),
 (4114, 0.030429030972509225),
 (4113, 0.03268602252303067),
 (4112, 0.0),
 (4111, 0.0),
 (4110, 0.028583097523751468),
 (4109, 0.0),
 (4108, 0.03333333333333333),
 (4107, 0.0),
 (4106, 0.024310831916315757),
 (4105, 0.0),
 (4104, 0.04714045207910317),
 (4103, 0.0),
 (4102, 0.0),
 (4101, 0.021698151830137312),
 (4100, 0.07647191129018724),
 (4099, 0.0),
 (4098, 0.1111111111111111),
 (4097, 0.0),
 (4096, 0.0),
 (4095, 0.034020690871988585),
 (4094, 0.0),
 (4093, 0.0),
 (4092, 0.0314970394174356),
 (4091, 0.06804138174397717),
 (4090, 0.0),
 (4089, 0.0),
 (4088, 0.0),
 (4087, 0.0),
 (4086, 0.032075014954979206),
 (4085, 0.05479966243511909),
 (4084, 0.07808688094430304),
 (4083, 0.0),
 (4082, 0.0),
 (4081, 0.025717224993681984),
 (4080, 0.10959932487023819),
 (4079, 0.028583097523751468),
 (4078, 0.043768810953240846),
 (4077, 0.04042260417272216),
 (4076, 0.046225016352102424),
 (4075, 0.0),
 (4074, 0.0),
 (4073, 0.0),
 (4072, 0.0),
 (4071, 0.0),
 (4070, 0.0),
 (4069, 0.02457365935914952),
 (4068, 0.025125945381480302),
 (4067, 0.036369648372665396),
 (4066, 0.030949223029508643),
 (4065, 0.0),
 (4064, 0.050251890762960605),
 (4063, 0.048112522432468816),
 (4062, 0.08084520834544431),
 (4061, 0.0),
 (4060, 0.0),
 (4059, 0.0),
 (4058, 0.0),
 (4057, 0.0),
 (4056, 0.08111071056538127),
 (4055, 0.0),
 (4054, 0.0),
 (4053, 0.050251890762960605),
 (4052, 0.021698151830137312),
 (4051, 0.0),
 (4050, 0.0),
 (4049, 0.19205531989934396),
 (4048, 0.0),
 (4047, 0.0),
 (4046, 0.10411584125907071),
 (4045, 0.041666666666666664),
 (4044, 0.0),
 (4043, 0.0),
 (4042, 0.0),
 (4041, 0.0),
 (4040, 0.029462782549439476),
 (4039, 0.06666666666666667),
 (4038, 0.029934217004462485),
 (4037, 0.046225016352102424),
 (4036, 0.0),
 (4035, 0.0),
 (4034, 0.0),
 (4033, 0.0),
 (4032, 0.0),
 (4031, 0.03726779962499649),
 (4030, 0.036369648372665396),
 (4029, 0.01950685786602176),
 (4028, 0.0),
 (4027, 0.041666666666666664),
 (4026, 0.036369648372665396),
 (4025, 0.0),
 (4024, 0.0314970394174356),
 (4023, 0.027036903521793755),
 (4022, 0.022680460581325723),
 (4021, 0.0),
 (4020, 0.018993429409939658),
 (4019, 0.11470786693528086),
 (4018, 0.022075539284417398),
 (4017, 0.0),
 (4016, 0.0),
 (4015, 0.0),
 (4014, 0.025416428388767443),
 (4013, 0.041666666666666664),
 (4012, 0.0),
 (4011, 0.16169041669088863),
 (4010, 0.029012942659282975),
 (4009, 0.0),
 (4008, 0.0),
 (4007, 0.07647191129018724),
 (4006, 0.0),
 (4005, 0.024056261216234408),
 (4004, 0.0),
 (4003, 0.018633899812498245),
 (4002, 0.0),
 (4001, 0.11470786693528086),
 (4000, 0.13900960937138318),
 (3999, 0.0),
 (3998, 0.024310831916315757),
 (3997, 0.0),
 (3996, 0.03268602252303067),
 (3995, 0.07647191129018724),
 (3994, 0.0200643088476282),
 (3993, 0.050251890762960605),
 (3992, 0.026352313834736494),
 (3991, 0.025416428388767443),
 (3990, 0.0),
 (3989, 0.0445435403187374),
 (3988, 0.03268602252303067),
 (3987, 0.0),
 (3986, 0.0),
 (3985, 0.0),
 (3984, 0.03333333333333333),
 (3983, 0.07647191129018724),
 (3982, 0.01540833878403414),
 (3981, 0.0),
 (3980, 0.03726779962499649),
 (3979, 0.046225016352102424),
 (3978, 0.034752402342845795),
 (3977, 0.07273929674533079),
 (3976, 0.0),
 (3975, 0.0),
 (3974, 0.0),
 (3973, 0.03823595564509362),
 (3972, 0.03726779962499649),
 (3971, 0.0),
 (3970, 0.0),
 (3969, 0.03268602252303067),
 (3968, 0.0),
 (3967, 0.0),
 (3966, 0.0),
 (3965, 0.0),
 (3964, 0.023112508176051212),
 (3963, 0.043033148291193514),
 (3962, 0.021166687833365082),
 (3961, 0.0),
 (3960, 0.0),
 (3959, 0.0),
 (3958, 0.0),
 (3957, 0.0314970394174356),
 (3956, 0.04042260417272216),
 (3955, 0.10910894511799618),
 (3954, 0.029934217004462485),
 (3953, 0.0),
 (3952, 0.03367175148507369),
 (3951, 0.023338001400466827),
 (3950, 0.046225016352102424),
 (3949, 0.03726779962499649),
 (3948, 0.022680460581325723),
 (3947, 0.034020690871988585),
 (3946, 0.0),
 (3945, 0.0),
 (3944, 0.0),
 (3943, 0.0),
 (3942, 0.0),
 (3941, 0.0),
 (3940, 0.0),
 (3939, 0.0),
 (3938, 0.050251890762960605),
 (3937, 0.0),
 (3936, 0.05986843400892497),
 (3935, 0.027777777777777776),
 (3934, 0.0),
 (3933, 0.025416428388767443),
 (3932, 0.06804138174397717),
 (3931, 0.026352313834736494),
 (3930, 0.036369648372665396),
 (3929, 0.0),
 (3928, 0.0),
 (3927, 0.06085806194501845),
 (3926, 0.027777777777777776),
 (3925, 0.03268602252303067),
 (3924, 0.048112522432468816),
 (3923, 0.0),
 (3922, 0.04042260417272216),
 (3921, 0.0),
 (3920, 0.0),
 (3919, 0.04042260417272216),
 (3918, 0.0314970394174356),
 (3917, 0.02817180849095055),
 (3916, 0.0),
 (3915, 0.0445435403187374),
 (3914, 0.020998026278290397),
 (3913, 0.027036903521793755),
 (3912, 0.0),
 (3911, 0.08703882797784893),
 (3910, 0.0),
 (3909, 0.0),
 (3908, 0.07715167498104596),
 (3907, 0.0),
 (3906, 0.06350006350009524),
 (3905, 0.02817180849095055),
 (3904, 0.0),
 (3903, 0.0),
 (3902, 0.034752402342845795),
 (3901, 0.03268602252303067),
 (3900, 0.0),
 (3899, 0.0),
 (3898, 0.0),
 (3897, 0.048112522432468816),
 (3896, 0.0),
 (3895, 0.0),
 (3894, 0.0),
 (3893, 0.019779694303230885),
 (3892, 0.03823595564509362),
 (3891, 0.06189844605901729),
 (3890, 0.0),
 (3889, 0.050251890762960605),
 (3888, 0.034020690871988585),
 (3887, 0.0),
 (3886, 0.048112522432468816),
 (3885, 0.0),
 (3884, 0.0),
 (3883, 0.0),
 (3882, 0.048621663832631515),
 (3881, 0.0),
 (3880, 0.024845199749997663),

In [94]:
# we see that the sorting has happened but not on similarity values but index values ..to fix this problem
sorted(list(enumerate(similarity[0])),reverse = True,key= lambda x : x[1])   # this tells the sorted function
# to do the sorting based on second number(value at 1st index ) rather than 1st number (value at 0th index)

[(0, 1.0000000000000002),
 (539, 0.25724787771376323),
 (1194, 0.2545875386086578),
 (507, 0.24498947175305572),
 (1216, 0.24459979523511427),
 (582, 0.24056261216234406),
 (1920, 0.24019223070763068),
 (260, 0.23947373603569988),
 (3731, 0.23570226039551587),
 (1444, 0.2311250817605121),
 (322, 0.22222222222222227),
 (74, 0.22116293423234568),
 (3609, 0.22075539284417395),
 (83, 0.2187974872468418),
 (61, 0.2182178902359924),
 (4194, 0.2182178902359924),
 (1537, 0.2166445612065605),
 (1204, 0.21629522817435004),
 (2333, 0.21428571428571427),
 (47, 0.21339479988815996),
 (495, 0.2132007163556104),
 (972, 0.2130032168075646),
 (2409, 0.21081851067789195),
 (2972, 0.21004201260420144),
 (942, 0.20953951903123735),
 (466, 0.20851441405707477),
 (1329, 0.20851441405707477),
 (2204, 0.20309059861498083),
 (151, 0.20211302086361077),
 (973, 0.20008168266626025),
 (1201, 0.19999999999999998),
 (1275, 0.196116135138184),
 (2787, 0.19245008972987526),
 (3000, 0.19245008972987526),
 (4407, 0.19245008972987526),
 (4049, 0.19205531989934396),
 (3539, 0.19179881852291683),
 (36, 0.1917988185229168),
 (3328, 0.1911797782254681),
 (305, 0.19050019050028574),
 (3163, 0.19047619047619047),
 (931, 0.18898223650461357),
 (1321, 0.18633899812498245),
 (150, 0.18605210188381271),
 (27, 0.1849000654084097),
 (300, 0.18446619684315546),
 (1071, 0.18446619684315546),
 (220, 0.18257418583505536),
 (461, 0.181848241863327),
 (301, 0.1805787796286538),
 (4, 0.1800205749557739),
 (184, 0.1800205749557739),
 (67, 0.17960530202677488),
 (46, 0.17407765595569785),
 (7, 0.17391639824998364),
 (373, 0.17376201171422898),
 (2496, 0.17376201171422898),
 (2732, 0.17376201171422898),
 (1831, 0.17201561551404662),
 (1344, 0.1714985851425088),
 (149, 0.17071583991052797),
 (26, 0.1690308509457033),
 (1808, 0.1690308509457033),
 (661, 0.16798421022632318),
 (108, 0.16666666666666666),
 (208, 0.16666666666666666),
 (838, 0.16666666666666666),
 (94, 0.16343011261515333),
 (581, 0.16343011261515333),
 (1396, 0.1617875572323585),
 (4011, 0.16169041669088863),
 (31, 0.16037507477489604),
 (2515, 0.16037507477489604),
 (1297, 0.16012815380508713),
 (1383, 0.16012815380508713),
 (4338, 0.16012815380508713),
 (168, 0.15811388300841897),
 (91, 0.15474611514754322),
 (3355, 0.15474611514754322),
 (311, 0.15430334996209188),
 (1965, 0.15319083833634298),
 (577, 0.15214515486254612),
 (3629, 0.15214515486254612),
 (158, 0.15075567228888181),
 (502, 0.15075567228888181),
 (1355, 0.15075567228888181),
 (111, 0.1496710850223124),
 (1178, 0.1496710850223124),
 (2169, 0.1496710850223124),
 (172, 0.14907119849998596),
 (490, 0.14907119849998596),
 (17, 0.1481668148335556),
 (1938, 0.1474419561548971),
 (422, 0.14547859349066158),
 (1488, 0.14547859349066158),
 (52, 0.14506471329641488),
 (41, 0.14433756729740643),
 (84, 0.14360673947588817),
 (332, 0.14291548761875733),
 (369, 0.14291548761875733),
 (568, 0.14291548761875733),
 (2687, 0.14291548761875733),
 (56, 0.14213381090374028),
 (249, 0.14213381090374028),
 (505, 0.14213381090374028),
 (2584, 0.14213381090374028),
 (557, 0.14085904245475275),
 (1220, 0.14085904245475275),
 (1322, 0.14002800840280097),
 (487, 0.13900960937138318),
 (1327, 0.13900960937138318),
 (4000, 0.13900960937138318),
 (187, 0.1388888888888889),
 (413, 0.1388888888888889),
 (1945, 0.1388888888888889),
 (1673, 0.1386750490563073),
 (4350, 0.1386750490563073),
 (2874, 0.13867504905630726),
 (2133, 0.13736056394868904),
 (1833, 0.13608276348795434),
 (2620, 0.13608276348795434),
 (2971, 0.13608276348795434),
 (4493, 0.13608276348795434),
 (1015, 0.13518451760896877),
 (3410, 0.13518451760896877),
 (3623, 0.13518451760896877),
 (342, 0.13471506281091267),
 (127, 0.13471506281091264),
 (2480, 0.1336306209562122),
 (595, 0.13344012817090595),
 (1299, 0.13344012817090595),
 (1479, 0.13344012817090595),
 (68, 0.13333333333333333),
 (134, 0.13333333333333333),
 (368, 0.13333333333333333),
 (1158, 0.13333333333333333),
 (1002, 0.13245323570650439),
 (3676, 0.13176156917368248),
 (1047, 0.13074409009212268),
 (1096, 0.13074409009212268),
 (1658, 0.13074409009212268),
 (1747, 0.13074409009212268),
 (2378, 0.13074409009212268),
 (3377, 0.13074409009212268),
 (740, 0.1301448015738384),
 (1715, 0.12909944487358055),
 (529, 0.12858612496840993),
 (778, 0.12858612496840993),
 (1037, 0.12858612496840993),
 (1617, 0.12858612496840993),
 (483, 0.12830005981991682),
 (420, 0.1270821419438372),
 (1741, 0.1270001270001905),
 (238, 0.1259881576697424),
 (939, 0.1259881576697424),
 (4676, 0.1259881576697424),
 (228, 0.1256297269074015),
 (2714, 0.1256297269074015),
 (3310, 0.1256297269074015),
 (4205, 0.125),
 (432, 0.12422599874998833),
 (549, 0.12422599874998831),
 (3408, 0.1242259987499883),
 (28, 0.12379689211803457),
 (1274, 0.12379689211803457),
 (2075, 0.12379689211803457),
 (2869, 0.12379689211803457),
 (95, 0.12286829679574761),
 (454, 0.1228682967957476),
 (50, 0.1217161238900369),
 (72, 0.1217161238900369),
 (275, 0.1217161238900369),
 (579, 0.1217161238900369),
 (1982, 0.1217161238900369),
 (1512, 0.1215541595815788),
 (123, 0.12155415958157878),
 (2547, 0.12155415958157878),
 (624, 0.12126781251816647),
 (653, 0.12126781251816647),
 (808, 0.12126781251816647),
 (1575, 0.12126781251816647),
 (3148, 0.1203858530857692),
 (1277, 0.12028130608117205),
 (692, 0.11904761904761904),
 (2259, 0.11785113019775793),
 (3722, 0.11785113019775793),
 (169, 0.11785113019775792),
 (3631, 0.11785113019775792),
 (166, 0.1178511301977579),
 (232, 0.1178511301977579),
 (294, 0.1178511301977579),
 (687, 0.1178511301977579),
 (859, 0.1178511301977579),
 (1616, 0.1178511301977579),
 (1574, 0.11704114719613055),
 (5, 0.11669000700233413),
 (10, 0.1160517706371319),
 (87, 0.1160517706371319),
 (1031, 0.1160517706371319),
 (3009, 0.1160517706371319),
 (81, 0.11547005383792512),
 (141, 0.11470786693528086),
 (627, 0.11470786693528086),
 (1373, 0.11470786693528086),
 (2323, 0.11470786693528086),
 (4001, 0.11470786693528086),
 (4019, 0.11470786693528086),
 (199, 0.11446713662390752),
 (14, 0.11433239009500587),
 (126, 0.11433239009500587),
 (508, 0.11433239009500587),
 (513, 0.11433239009500587),
 (1195, 0.11433239009500587),
 (2583, 0.11433239009500587),
 (777, 0.11340230290662862),
 (854, 0.1126872339638022),
 (900, 0.1126872339638022),
 (2013, 0.1126872339638022),
 (2450, 0.1126872339638022),
 (3499, 0.1126872339638022),
 (35, 0.11180339887498947),
 (1524, 0.11180339887498947),
 (1721, 0.11180339887498947),
 (1727, 0.11180339887498947),
 (2634, 0.11180339887498947),
 (3664, 0.11180339887498947),
 (4136, 0.11180339887498947),
 (1497, 0.11135885079684349),
 (2106, 0.11135885079684349),
 (2439, 0.11135885079684349),
 (2761, 0.11135885079684349),
 (1082, 0.1111111111111111),
 (1294, 0.1111111111111111),
 (3341, 0.1111111111111111),
 (3621, 0.1111111111111111),
 (4098, 0.1111111111111111),
 (18, 0.11037769642208699),
 (102, 0.11037769642208699),
 (1019, 0.11037769642208699),
 (131, 0.10959932487023819),
 (174, 0.10959932487023819),
 (266, 0.10959932487023819),
 (330, 0.10959932487023819),
 (2072, 0.10959932487023819),
 (2181, 0.10959932487023819),
 (4080, 0.10959932487023819),
 (403, 0.10942202738310211),
 (3782, 0.1091089451179962),
 (325, 0.10910894511799618),
 (773, 0.10910894511799618),
 (1156, 0.10910894511799618),
 (2521, 0.10910894511799618),
 (3056, 0.10910894511799618),
 (3840, 0.10910894511799618),
 (3955, 0.10910894511799618),
 (239, 0.10849075915068655),
 (295, 0.10814761408717502),
 (312, 0.10814761408717502),
 (535, 0.10814761408717502),
 (754, 0.10814761408717502),
 (1273, 0.10814761408717502),
 (3103, 0.10814761408717502),
 (4232, 0.10814761408717502),
 (988, 0.10675210253672475),
 (139, 0.10669739994407998),
 (105, 0.10660035817780521),
 (233, 0.10660035817780521),
 (476, 0.10660035817780521),
 (2456, 0.10660035817780521),
 (2562, 0.10660035817780521),
 (2763, 0.10660035817780521),
 (4200, 0.10660035817780521),
 (4626, 0.10660035817780521),
 (4548, 0.10583343916682542),
 (182, 0.10540925533894598),
 (334, 0.10540925533894598),
 (643, 0.10540925533894598),
 (1056, 0.10540925533894598),
 (1109, 0.10540925533894598),
 (3784, 0.10540925533894598),
 (33, 0.10425720702853739),
 (85, 0.10425720702853739),
 (148, 0.10425720702853739),
 (157, 0.10425720702853739),
 (263, 0.10425720702853739),
 (715, 0.10425720702853739),
 (935, 0.10425720702853739),
 (1280, 0.10425720702853739),
 (1301, 0.10425720702853739),
 (1501, 0.10425720702853739),
 (2660, 0.10425720702853739),
 (4333, 0.10425720702853739),
 (510, 0.10411584125907071),
 (898, 0.10411584125907071),
 (1086, 0.10411584125907071),
 (4046, 0.10411584125907071),
 (307, 0.10314212462587934),
 (129, 0.10286889997472794),
 (279, 0.10286889997472794),
 (1233, 0.10286889997472794),
 (3444, 0.10286889997472794),
 (3465, 0.10286889997472794),
 (400, 0.10206207261596575),
 (660, 0.10206207261596575),
 (781, 0.10206207261596575),
 (920, 0.10206207261596575),
 (1306, 0.10206207261596575),
 (1942, 0.10206207261596575),
 (2661, 0.10206207261596575),
 (4258, 0.10206207261596575),
 (371, 0.10166571355506977),
 (870, 0.10166571355506977),
 (1439, 0.10166571355506977),
 (270, 0.10050378152592121),
 (278, 0.10050378152592121),
 (410, 0.10050378152592121),
 (412, 0.10050378152592121),
 (473, 0.10050378152592121),
 (813, 0.10050378152592121),
 (933, 0.10050378152592121),
 (1202, 0.10050378152592121),
 (1276, 0.10050378152592121),
 (1823, 0.10050378152592121),
 (1846, 0.10050378152592121),
 (2003, 0.10050378152592121),
 (2284, 0.10050378152592121),
 (292, 0.1),
 (530, 0.1),
 (564, 0.1),
 (691, 0.1),
 (791, 0.1),
 (1077, 0.1),
 (2651, 0.1),
 (3094, 0.1),
 (3737, 0.1),
 (243, 0.09829463743659808),
 (785, 0.09820927516479827),
 (1089, 0.09820927516479827),
 (142, 0.09805806756909201),
 (389, 0.09805806756909201),
 (1474, 0.09805806756909201),
 (1589, 0.09805806756909201),
 (1686, 0.09805806756909201),
 (1756, 0.09805806756909201),
 (2396, 0.09805806756909201),
 (2652, 0.09805806756909201),
 (1357, 0.09724332766526303),
 (2596, 0.09724332766526303),
 (43, 0.09622504486493763),
 (618, 0.09622504486493763),
 (2488, 0.09622504486493763),
 (2797, 0.09622504486493763),
 (3155, 0.09622504486493763),
 (122, 0.09622504486493762),
 (236, 0.09622504486493762),
 (362, 0.09622504486493762),
 (1027, 0.09622504486493762),
 (1408, 0.09622504486493762),
 (2093, 0.09622504486493762),
 (206, 0.09558988911273406),
 (1418, 0.09523809523809523),
 (160, 0.09496714704969829),
 (12, 0.0944911182523068),
 (23, 0.0944911182523068),
 (511, 0.0944911182523068),
 (922, 0.0944911182523068),
 (2841, 0.0944911182523068),
 (1832, 0.09428090415820634),
 (1924, 0.09428090415820634),
 (479, 0.09375732507716866),
 (596, 0.09335200560186731),
 (1278, 0.09335200560186731),
 (21, 0.09284766908852593),
 (242, 0.09284766908852593),
 (306, 0.09284766908852593),
 (794, 0.09284766908852593),
 (960, 0.09284766908852593),
 (980, 0.09284766908852593),
 (1004, 0.09284766908852593),
 (1523, 0.09284766908852593),
 (2818, 0.09284766908852593),
 (3429, 0.09284766908852593),
 (4471, 0.09284766908852593),
 (799, 0.09259259259259259),
 (1496, 0.09245003270420485),
 (2388, 0.09245003270420485),
 (2857, 0.09245003270420485),
 (4355, 0.09245003270420485),
 (4505, 0.09245003270420485),
 (4519, 0.09245003270420485),
 (4657, 0.09245003270420485),
 (2448, 0.09147021665807528),
 (164, 0.09128709291752768),
 (227, 0.09128709291752768),
 (315, 0.09128709291752768),
 (349, 0.09128709291752768),
 (901, 0.09128709291752768),
 (1249, 0.09128709291752768),
 (1378, 0.09128709291752768),
 (1700, 0.09128709291752768),
 (1790, 0.09128709291752768),
 (3538, 0.09128709291752768),
 (3817, 0.09128709291752768),
 (4629, 0.09128709291752768),
 (63, 0.09072184232530289),
 (107, 0.09072184232530289),
 (170, 0.09072184232530289),
 (812, 0.09072184232530289),
 (2005, 0.09072184232530289),
 (2969, 0.09072184232530289),
 (32, 0.08989331499509895),
 (45, 0.08989331499509895),
 (467, 0.08989331499509895),
 (491, 0.08989331499509895),
 (75, 0.08980265101338746),
 (88, 0.08980265101338746),
 (112, 0.08980265101338746),
 (245, 0.08980265101338746),
 (356, 0.08980265101338746),
 (626, 0.08980265101338746),
 (775, 0.08980265101338746),
 (814, 0.08980265101338746),
 (894, 0.08980265101338746),
 (1269, 0.08980265101338746),
 (2167, 0.08980265101338746),
 (3302, 0.08980265101338746),
 (3450, 0.08980265101338746),
 (222, 0.0890870806374748),
 (363, 0.0890870806374748),
 (381, 0.0890870806374748),
 (2274, 0.0890870806374748),
 (2339, 0.0890870806374748),
 (2498, 0.0890870806374748),
 (2881, 0.0890870806374748),
 (4740, 0.0890870806374748),
 (2386, 0.08883363181483767),
 (1, 0.08838834764831843),
 (96, 0.08838834764831843),
 (121, 0.08838834764831843),
 (241, 0.08838834764831843),
 (547, 0.08838834764831843),
 (1142, 0.08838834764831843),
 (2247, 0.08838834764831843),
 (2251, 0.08838834764831843),
 (2304, 0.08838834764831843),
 (3092, 0.08838834764831843),
 (4261, 0.08838834764831843),
 (4660, 0.08838834764831843),
 (230, 0.08830215713766959),
 (654, 0.08830215713766959),
 (103, 0.08753762190648169),
 (1878, 0.08753762190648169),
 (3442, 0.08753762190648169),
 (39, 0.08703882797784893),
 (86, 0.08703882797784893),
 (101, 0.08703882797784893),
 (203, 0.08703882797784893),
 (543, 0.08703882797784893),
 (786, 0.08703882797784893),
 (899, 0.08703882797784893),
 (1113, 0.08703882797784893),
 (1207, 0.08703882797784893),
 (2795, 0.08703882797784893),
 (3911, 0.08703882797784893),
 (193, 0.08679260732054925),
 (501, 0.08679260732054925),
 (1282, 0.08679260732054925),
 (19, 0.08606629658238703),
 (1139, 0.08606629658238703),
 (1621, 0.08606629658238703),
 (2099, 0.08606629658238703),
 (2250, 0.08606629658238703),
 (3070, 0.08606629658238703),
 (3219, 0.08606629658238703),
 (4495, 0.08606629658238703),
 (4721, 0.08606629658238703),
 (257, 0.08574929257125441),
 (634, 0.08574929257125441),
 (746, 0.08574929257125441),
 (787, 0.08574929257125441),
 (1473, 0.08574929257125441),
 (3029, 0.08574929257125441),
 (3141, 0.08574929257125441),
 (3236, 0.08574929257125441),
 (3311, 0.08574929257125441),
 (3424, 0.08574929257125441),
 (51, 0.08535791995526398),
 (1405, 0.08535791995526398),
 (1534, 0.08535791995526398),
 (1828, 0.08535791995526398),
 (1898, 0.08535791995526398),
 (153, 0.08466675133346033),
 (572, 0.08466675133346033),
 (1926, 0.08466675133346033),
 (2203, 0.08466675133346033),
 (70, 0.08451542547285165),
 (98, 0.08451542547285165),
 (207, 0.08451542547285165),
 (457, 0.08451542547285165),
 (885, 0.08451542547285165),
 (937, 0.08451542547285165),
 (1161, 0.08451542547285165),
 (2253, 0.08451542547285165),
 (3390, 0.08451542547285165),
 (589, 0.08399210511316159),
 (1639, 0.08399210511316159),
 (3432, 0.08399210511316159),
 (472, 0.08333333333333333),
 (503, 0.08333333333333333),
 (534, 0.08333333333333333),
 (752, 0.08333333333333333),
 (776, 0.08333333333333333),
 (987, 0.08333333333333333),
 (1401, 0.08333333333333333),
 (1655, 0.08333333333333333),
 (2165, 0.08333333333333333),
 (2644, 0.08333333333333333),
 (2802, 0.08333333333333333),
 (2883, 0.08333333333333333),
 (3356, 0.08333333333333333),
 (3528, 0.08333333333333333),
 (4167, 0.08333333333333333),
 (4433, 0.08333333333333333),
 (4476, 0.08333333333333333),
 (4644, 0.08333333333333333),
 (190, 0.08268982305947231),
 (37, 0.08219949365267865),
 (82, 0.08219949365267865),
 (223, 0.08219949365267865),
 (329, 0.08219949365267865),
 (471, 0.08219949365267865),
 (680, 0.08219949365267865),
 (1614, 0.08219949365267865),
 (2684, 0.08219949365267865),
 (3471, 0.08219949365267865),
 (2764, 0.08206099398622181),
 (16, 0.08111071056538127),
 (71, 0.08111071056538127),
 (138, 0.08111071056538127),
 (254, 0.08111071056538127),
 (632, 0.08111071056538127),
 (1290, 0.08111071056538127),
 (1560, 0.08111071056538127),
 (1765, 0.08111071056538127),
 (2821, 0.08111071056538127),
 (4056, 0.08111071056538127),
 (62, 0.08084520834544431),
 (189, 0.08084520834544431),
 (205, 0.08084520834544431),
 (256, 0.08084520834544431),
 (850, 0.08084520834544431),
 (1045, 0.08084520834544431),
 (1323, 0.08084520834544431),
 (1664, 0.08084520834544431),
 (2161, 0.08084520834544431),
 (2326, 0.08084520834544431),
 (2713, 0.08084520834544431),
 (2790, 0.08084520834544431),
 (3156, 0.08084520834544431),
 (3254, 0.08084520834544431),
 (3431, 0.08084520834544431),
 (3833, 0.08084520834544431),
 (4062, 0.08084520834544431),
 (4571, 0.08084520834544431),
 (11, 0.08006407690254357),
 (365, 0.08006407690254357),
 (1289, 0.08006407690254357),
 (1367, 0.08006407690254357),
 (2592, 0.08006407690254357),
 (3207, 0.08006407690254357),
 (3702, 0.08006407690254357),
 (4454, 0.08006407690254357),
 (274, 0.07945521577046602),
 (59, 0.07911877721292354),
 (737, 0.07905694150420949),
 (2163, 0.07905694150420949),
 (4643, 0.07905694150420949),
 (125, 0.07874259854358899),
 (109, 0.07856742013183862),
 (200, 0.07856742013183862),
 (313, 0.07856742013183862),
 (800, 0.07856742013183862),
 (1288, 0.07856742013183862),
 (1348, 0.07856742013183862),
 (1521, 0.07856742013183862),
 (2317, 0.07856742013183862),
 (2381, 0.07856742013183862),
 (2410, 0.07856742013183862),
 (2551, 0.07856742013183862),
 (2659, 0.07856742013183862),
 (4414, 0.07856742013183862),
 (79, 0.07808688094430304),
 (271, 0.07808688094430304),
 (587, 0.07808688094430304),
 (665, 0.07808688094430304),
 (732, 0.07808688094430304),
 (908, 0.07808688094430304),
 (2395, 0.07808688094430304),
 (2832, 0.07808688094430304),
 (2917, 0.07808688094430304),
 (4084, 0.07808688094430304),
 (229, 0.07802743146408704),
 (55, 0.07749842582921285),
 (591, 0.07715167498104596),
 (1175, 0.07715167498104596),
 (1325, 0.07715167498104596),
 (2052, 0.07715167498104596),
 (2363, 0.07715167498104596),
 (2702, 0.07715167498104596),
 (3023, 0.07715167498104596),
 (3908, 0.07715167498104596),
 (4124, 0.07715167498104596),
 (2354, 0.07715167498104594),
 (179, 0.07647191129018724),
 (1005, 0.07647191129018724),
 (1769, 0.07647191129018724),
 (2136, 0.07647191129018724),
 (2212, 0.07647191129018724),
 (2788, 0.07647191129018724),
 (3073, 0.07647191129018724),
 (3399, 0.07647191129018724),
 (3983, 0.07647191129018724),
 (3995, 0.07647191129018724),
 (4007, 0.07647191129018724),
 (4100, 0.07647191129018724),
 (9, 0.07624928516630233),
 (76, 0.07624928516630233),
 (536, 0.07624928516630233),
 (674, 0.07624928516630233),
 (784, 0.07624928516630233),
 (1623, 0.07624928516630233),
 (2021, 0.07624928516630233),
 (2241, 0.07624928516630233),
 (3189, 0.07624928516630233),
 (488, 0.07548513560963971),
 (212, 0.07537783614444091),
 (782, 0.07537783614444091),
 (1446, 0.07537783614444091),
 (1632, 0.07537783614444091),
 (1883, 0.07537783614444091),
 (2650, 0.07537783614444091),
 (97, 0.07453559924999299),
 (419, 0.07453559924999299),
 (635, 0.07453559924999299),
 (728, 0.07453559924999299),
 (827, 0.07453559924999299),
 (979, 0.07453559924999299),
 (1168, 0.07453559924999299),
 (3391, 0.07453559924999299),
 (570, 0.07453559924999298),
 (1292, 0.07453559924999298),
 (1770, 0.07453559924999298),
 (2699, 0.07453559924999298),
 (4405, 0.07453559924999298),
 (4446, 0.07453559924999298),
 (997, 0.07372097807744857),
 (1018, 0.07372097807744857),
 (1146, 0.07372097807744857),
 (1701, 0.07372097807744857),
 (2056, 0.07372097807744857),
 (3823, 0.07372097807744857),
 (183, 0.07362101738323101),
 (215, 0.07293249574894728),
 (704, 0.07293249574894728),
 (1340, 0.07293249574894728),
 (1996, 0.07293249574894728),
 (2018, 0.07293249574894728),
 (2320, 0.07293249574894728),
 (100, 0.07273929674533079),
 (336, 0.07273929674533079),
 (1166, 0.07273929674533079),
 (1171, 0.07273929674533079),
 (1262, 0.07273929674533079),
 (1737, 0.07273929674533079),
 (1774, 0.07273929674533079),
 (1990, 0.07273929674533079),
 (2114, 0.07273929674533079),
 (2533, 0.07273929674533079),
 (3242, 0.07273929674533079),
 (3672, 0.07273929674533079),
 (3977, 0.07273929674533079),
 (4292, 0.07273929674533079),
 (30, 0.07216878364870322),
 (281, 0.07216878364870322),
 (3226, 0.07216878364870322),
 (3561, 0.07216878364870322),
 (4345, 0.07216878364870322),

In [95]:
# the top 5 movies
sorted(list(enumerate(similarity[0])),reverse = True,key= lambda x : x[1])[1:6]

[(539, 0.25724787771376323),
 (1194, 0.2545875386086578),
 (507, 0.24498947175305572),
 (1216, 0.24459979523511427),
 (582, 0.24056261216234406)]

In [96]:
'''def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key = lambda x: x[1])[1:6]  # to take the first five values
    
    for i in movies_list:
        
        print(i[0])'''

"def recommend(movie):\n    movie_index = new_df[new_df['title'] == movie].index[0]\n    distances = similarity[movie_index]\n    movies_list = sorted(list(enumerate(distances)),reverse=True,key = lambda x: x[1])[1:6]  # to take the first five values\n    \n    for i in movies_list:\n        \n        print(i[0])"

In [97]:
#recommend('Avatar')

In [98]:
#new_df.iloc[1216]

In [99]:
#new_df.iloc[1216].title

In [100]:
def recommend(movie):
    movie=movie.lower()
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key = lambda x: x[1])[1:6]  # to take the first five values
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)     # now this will print the movies titles ..instead of the movie indexes of
                                           # top five similar movies

In [101]:
recommend('Avatar')

titan a.e.
small soldiers
independence day
aliens vs predator: requiem
battle: los angeles

In [102]:
recommend('Batman Begins')

the dark knight
the dark knight rises
batman
batman & robin
batman

In [103]:
recommend('Spiderman')

IndexError: index 0 is out of bounds for axis 0 with size 0

In [104]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [105]:
recommend('John Carter')

star trek: insurrection
mission to mars
captain america: the first avenger
escape from planet earth
ghosts of mars

In [106]:
import pickle

In [107]:
pickle.dump(new_df,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [108]:
movies.overview[0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.']

In [109]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [110]:
movies.title

0                                         Avatar
1       Pirates of the Caribbean: At World's End
2                                        Spectre
3                          The Dark Knight Rises
4                                    John Carter
                          ...
4804                                 El Mariachi
4805                                   Newlyweds
4806                   Signed, Sealed, Delivered
4807                            Shanghai Calling
4808                           My Date with Drew
Name: title, Length: 4809, dtype: object

In [111]:
'Avatar'.overview

AttributeError: 'str' object has no attribute 'overview'

In [112]:
movies['index']

KeyError: 'index'

In [113]:
movies['title'][0]

'Avatar'

In [114]:
def return_index(movie_name):
    for i in range(4808):
        if(movies['title'][i]==movie_name):
            return i

In [115]:
def fetching_details(movie_name):
    index = return_index(movie_name)
    cast = movies.cast[index]
    genres = movies.genres[index]
    overview = movies.overview[index]
    print("Cast : ",cast)
    print("Genres : " ,genres)
    print("Overview : ",overview)

In [116]:
fetching_details('John Carter')

Cast :  ['TaylorKitsch', 'LynnCollins', 'SamanthaMorton']
Genres :  ['Action', 'Adventure', 'ScienceFiction']
Overview :  ['John', 'Carter', 'is', 'a', 'war-weary,', 'former', 'military', 'captain', "who's", 'inexplicably', 'transported', 'to', 'the', 'mysterious', 'and', 'exotic', 'planet', 'of', 'Barsoom', '(Mars)', 'and', 'reluctantly', 'becomes', 'embroiled', 'in', 'an', 'epic', 'conflict.', "It's", 'a', 'world', 'on', 'the', 'brink', 'of', 'collapse,', 'and', 'Carter', 'rediscovers', 'his', 'humanity', 'when', 'he', 'realizes', 'the', 'survival', 'of', 'Barsoom', 'and', 'its', 'people', 'rests', 'in', 'his', 'hands.']

In [117]:
import pickle

In [118]:
pickle.dump(new_df, open('movies.pkl', 'wb'))

In [123]:
new_df['title'].values

array(['avatar', "pirates of the caribbean: at world's end", 'spectre',
       ..., 'signed, sealed, delivered', 'shanghai calling',
       'my date with drew'], dtype=object)

In [125]:
pickle.dump(new_df.to_dict(), open('movie_dict.pkl', 'wb'))

In [127]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [128]:
new_df.head()

,movie_id,title,tags
0,19995,avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,pirates of the caribbean: at world's end,"captain barbossa, long believ to be dead, ha c..."
2,206647,spectre,a cryptic messag from bond’ past send him on a...
3,49026,the dark knight rises,follow the death of district attorney harvey d...
4,49529,john carter,"john carter is a war-weary, former militari ca..."